gapi.loaded_0(function(_){var window=this;
try{
_.l=function(a){throw a;};_.n=void 0;_.q=!0;_.r=null;_.t=!1;_.aa=function(){return function(a){return a}};_.v=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.x=function(a){return function(){return this[a]}};_.y=function(a){return function(){return a}};
_.ca=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.da=function(a){return a!==_.n};_.ea=function(a){return"array"==(0,_.ca)(a)};_.fa=function(a){var c=typeof a;return"object"==c&&a!=_.r||"function"==c};_.ga=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.ha=function(a,c,f){a||(0,_.l)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.D=function(a,c,f){_.D=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ga:_.ha;return _.D.apply(_.r,arguments)};
_.ia=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_.E=function(a,c){function f(){}f.prototype=c.prototype;a.p=c.prototype;a.prototype=new f;a.prototype.constructor=a};_._DumpException=function(a){(0,_.l)(a)};_.ja=_.ja||{};_.F=this;_.ka="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.la=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.D.apply(_.r,f)}return(0,_.D)(this,a)};
_.ma=window.gapi||{};_.oa=window.___jsl=window.___jsl||{};_.pa=_.oa.df=_.oa.df||{};_.qa=window.gadgets||{};_.J=window.osapi=window.osapi||{};
}catch(e){_._DumpException(e)}
try{
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.t},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.t},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"}},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.q,"pos.plusones.list":_.q,"pos.plusones.get":_.q,"chili.people.get":_.q,"pos.plusones.insert":_.q,"chili.activities.list":_.q,"pos.plusones.delete":_.q,"chili.activities.get":_.q,"chili.activities.search":_.q,"pos.plusones.getSignupState":_.q},requestCache:{enabled:_.q},versions:{chili:"v1",pos:"v1"},rpc:"/rpc", root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.q},transport:{isProxyShared:_.q},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.t}}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{card:{url:":socialhost:/u/:session_index:/_/hovercard/card"}}});

}catch(e){_._DumpException(e)}
try{
_.ra=window.__GOOGLEAPIS;if(_.ra){_.ra.googleapis&&!_.ra["googleapis.config"]&&(_.ra["googleapis.config"]=_.ra.googleapis);_.sa=window.___jsl=window.___jsl||{};(_.sa.ci=_.sa.ci||[]).push(_.ra);window.__GOOGLEAPIS=_.n};

}catch(e){_._DumpException(e)}
try{
_.ta=function(a,c,f){a=a.split(".");f=f||_.F;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.da)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};_.ua=function(){return window.___jsl=window.___jsl||{}};_.va=function(a){var c=(0,_.ua)();c[a]=c[a]||[];return c[a]};_.wa=function(a){var c=(0,_.ua)();c.cfg=!a&&c.cfg||{};return c.cfg};_.xa=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.ya=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.xa)(a[f])&&!(0,_.xa)(c[f])?(0,_.ya)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.xa)(c[f])?[]:{},(0,_.ya)(a[f],c[f])):a[f]=c[f])};_.za=function(a){if(a){var c="",f=a.nodeType;if(3==f||4==f)c=a.nodeValue;else if(a.innerText)c=a.innerText;else if(a.innerHTML)c=a.innerHTML;else if(a.firstChild){c=[];for(a=a.firstChild;a;a=a.nextSibling)c.push((0,_.za)(a));c=c.join("")}return c}};
_.Aa=function(a){(0,_.wa)(_.q);var c=window.___gcfg,f=(0,_.va)("cu");if(c&&c!==window.___gu){var g={};(0,_.ya)(g,c);f.push(g);window.___gu=c}var c=(0,_.va)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],k=[],m=(0,_.ua)().u;m&&k.push(m);(0,_.ua)().us&&k.push.apply(k,(0,_.ua)().us);for(m=0;m<h.length;++m)for(var p=h[m],s=0;s<k.length;++s)p.src&&0==p.src.indexOf(k[s])&&g.push(p);0==g.length&&h[h.length-1].src&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)if(!g[h].getAttribute("gapi_processed")){g[h].setAttribute("gapi_processed",
_.q);if(k=(0,_.za)(g[h])){for(;0==k.charCodeAt(k.length-1);)k=k.substring(0,k.length-1);m=_.n;try{m=(new window.Function("return ("+k+"\n)"))()}catch(u){}if("object"===typeof m)k=m;else{try{m=(new window.Function("return ({"+k+"\n})"))()}catch(w){}k="object"===typeof m?m:{}}}else k=_.n;k&&c.push(k)}a&&(g={},(0,_.ya)(g,a),f.push(g));g=(0,_.va)("cd");a=0;for(c=g.length;a<c;++a)(0,_.ya)((0,_.wa)(),g[a]);g=(0,_.va)("ci");a=0;for(c=g.length;a<c;++a)(0,_.ya)((0,_.wa)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.ya)((0,_.wa)(),
f[a])};_.L=function(a,c){if(!a)return(0,_.wa)();for(var f=a.split("/"),g=(0,_.wa)(),h=0,k=f.length;g&&"object"===typeof g&&h<k;++h)g=g[f[h]];return h===f.length&&g!==_.n?g:c};_.Ba=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),k=0,m=h.length;k<m-1;++k)var p={},g=g[h[k]]=p;g[h[k]]=c}(0,_.Aa)(f)};_.M=function(a,c){c="function"==typeof _.Ca&&(0,_.Ca)(a,c)||c;(0,_.ta)(a,c,_.n);var f=c;if(_.pa[a]){var g=_.pa[a];delete _.pa[a];g(f)}};
(0,_.Aa)();(0,_.M)("gapi.config.get",_.L);(0,_.M)("gapi.config.update",_.Ba);

}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.Ja={go:{},O:{}};_.Ka={go:{},O:{}};

}catch(e){_._DumpException(e)}
try{
_.La=window;_.Ma=window.document;

}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};

}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.O.yd=function(a,c,f){for(var g=[],h=2,k=arguments.length;h<k;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,k=arguments.length;h<k;++h)f.push(arguments[h]);return c.apply(a,f)}};_.O.se=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};


}catch(e){_._DumpException(e)}
try{
_.Ta=function(a,c){return window.String.fromCharCode(c)};_.O=_.O||{};_.Ua={"0":_.t,10:_.q,13:_.q,34:_.q,39:_.q,60:_.q,62:_.q,92:_.q,8232:_.q,8233:_.q,65282:_.q,65287:_.q,65308:_.q,65310:_.q,65340:_.q};_.O.escape=function(a,c){if(a){if("string"===typeof a)return _.O.Yd(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.O.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.O.Yd(g)]=_.O.escape(a[g],_.q));return f}}return a}; _.O.Yd=function(a){if(!a)return a;for(var c=[],f,g,h=0,k=a.length;h<k;++h)f=a.charCodeAt(h),g=_.Ua[f],g===_.q?c.push("&#",f,";"):g!==_.t&&c.push(a.charAt(h));return c.join("")};_.O.Iq=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.Ta)};


}catch(e){_._DumpException(e)}
try{
_.Wa=_.Wa||{};_.Wa.bn=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};


}catch(e){_._DumpException(e)}
try{
_.Xa=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.Wa=_.Wa||{};
_.Wa.zg=function(){var a=_.Wa.bn().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.r))?h.overflowY:_.r);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.r))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var k=h.offsetTop+h.offsetHeight+(0,_.Xa)(h,"margin-bottom"),a=window.Math.max(a,k);c.push(h)}}return a+(0,_.Xa)(window.document.body,"border-bottom")+(0,_.Xa)(window.document.body,"margin-bottom")+(0,_.Xa)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};


}catch(e){_._DumpException(e)}
try{
_.Pa=function(a,c){if(!(a<_.Qa)&&_._console$$inline_230)if(2===a&&_._console$$inline_230.warn)_._console$$inline_230.warn(c);else if(3===a&&_._console$$inline_230.error)try{_._console$$inline_230.error(c)}catch(f){}else _._console$$inline_230.log&&_._console$$inline_230.log(c)};_.Ra=function(a){(0,_.Pa)(1,a)};
_.Sa=function(a){(0,_.Pa)(2,a)};_.Ia=function(a){(0,_.Pa)(3,a)};_.Ra.INFO=1;_.Ra.WARNING=2;_.Ra.NONE=4;_.Qa=1;_._console$$inline_230=window.console?window.console:window.opera?window.opera.postError:_.n;

}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.O.Sd=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.Sa)("cannot attachBrowserEvent: "+c)};_.O.Bo=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.Sa)("cannot removeBrowserEvent: "+c)};


}catch(e){_._DumpException(e)}
try{
_.Ya=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;w=u=0}function c(a){for(var c=m,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;for(var a=h[0],g=h[1],k=h[2],p=h[3],u=h[4],s,w,f=0;80>f;f++)40>f?20>f?(s=p^g&(k^p),w=1518500249):(s=g^k^p,w=1859775393):60>f?(s=g&k|p&(g|k),w=2400959708):(s=g^k^p,w=3395469782),s=((a<<5|a>>>27)&4294967295)+
s+u+w+c[f]&4294967295,u=p,p=k,k=(g<<30|g>>>2)&4294967295,g=a,a=s;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+k&4294967295;h[3]=h[3]+p&4294967295;h[4]=h[4]+u&4294967295}function f(a,f){if("string"===typeof a){for(var a=(0,window.unescape)((0,window.encodeURIComponent)(a)),g=[],h=0,m=a.length;h<m;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==u)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64;for(;g<f;)if(k[u++]=a[g++],w++,64==u){u=0;for(c(k);g+64<f;)c(a.slice(g,g+64)),g+=64,w+=64}}
function g(){var a=[],g=8*w;56>u?f(p,56-u):f(p,64-(u-56));for(var m=63;56<=m;m--)k[m]=g&255,g>>>=8;c(k);for(m=g=0;5>m;m++)for(var s=24;0<=s;s-=8)a[g++]=h[m]>>s&255;return a}for(var h=[],k=[],m=[],p=[128],s=1;64>s;++s)p[s]=0;var u,w;a();return{reset:a,update:f,fq:g,Ne:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};


}catch(e){_._DumpException(e)}
try{
_.$a=function(a){var c=(0,_.Ya)();c.update(a);return c.Ne()};_.ab=window.crypto;
if(_.ab&&"function"==typeof _.ab.getRandomValues)_.Za=function(){var a=new window.Uint32Array(1);_.ab.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.bb=(0,_.L)("random/maxObserveMousemove");_.bb==_.r&&(_.bb=-1);_.cb=0;_.eb=window.Math.random();_.fb=1;_.gb=1E6*(window.screen.width*window.screen.width+window.screen.height);_.hb=function(a){var a=a||window.event,c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.fb=_.fb*c%_.gb;0<_.bb&&++_.cb==_.bb&&
_.O.Bo(window,"mousemove",_.hb,_.t)};0!=_.bb&&_.O.Sd(window,"mousemove",_.hb,_.t);_.ib=(0,_.$a)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.eb);_.Za=function(){var a=_.fb,a=a+(0,window.parseInt)(_.ib.substr(0,20),16);_.ib=(0,_.$a)(_.ib);return a/(_.gb+window.Math.pow(16,20))}};
(0,_.M)("shindig.random",_.Za);

}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.jb=[];_.O.vq=function(a){_.jb.push(a)};_.O.Bq=function(){for(var a=0,c=_.jb.length;a<c;++a)_.jb[a]()};

}catch(e){_._DumpException(e)}
try{
_.lb=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.lb&&(0,_.Ba)((0,_.lb)());_.kb={N:function(a,c,f){f&&f((0,_.L)())},get:function(a){return(0,_.L)(a)},update:function(a,c){c&&(0,_.l)("Config replacement is not supported");(0,_.Ba)(a)},S:(0,_.v)()};
(0,_.M)("gadgets.config.register",_.kb.N);(0,_.M)("gadgets.config.get",_.kb.get);(0,_.M)("gadgets.config.init",_.kb.S);(0,_.M)("gadgets.config.update",_.kb.update);

}catch(e){_._DumpException(e)}
try{
if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.Na=function(a){return this[a]};_.Oa=/___$/;_.N={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.t}},stringify:function(a){function c(a){return f.call(this,a,_.Na)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.Oa.test(a)?c:_.n})}catch(h){return _.r}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.N=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,k,m;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){m=a.length;for(k=0;k<m;k+=1)h.push(c(a[k])||"null");return"["+h.join(",")+"]"}for(k in a)!/___$/.test(k)&&a.hasOwnProperty(k)&&"string"===typeof k&&(m=c(a[k]))&&h.push(c(k)+":"+m);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.t}}}();
_.N.Di=function(a){var c={};if(a===_.r||a===_.n)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.r===g||_.n===g||(c[f]="string"===typeof g?g:_.N.stringify(g))}return c};(0,_.M)("gadgets.json.flatten",_.N.Di);(0,_.M)("gadgets.json.parse",_.N.parse);(0,_.M)("gadgets.json.stringify",_.N.stringify);(0,_.M)("gadgets.json.flatten",_.N.Di);(0,_.M)("gadgets.json.parse",_.N.parse);(0,_.M)("gadgets.json.stringify",_.N.stringify);


}catch(e){_._DumpException(e)}
try{
_.O=_.O||{};_.Va=_.r;
_.O.U=function(a){var c="undefined"===typeof a;if(_.Va!==_.r&&c)return _.Va;for(var f={},a=a||window.document.location.href,g=a.indexOf("?"),h=a.indexOf("#"),a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&"),g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,k=a.length;h<k;++h){var m=a[h].indexOf("=");if(-1!==m){var p=a[h].substring(0,m),m=a[h].substring(m+1),m=m.replace(/\+/g," ");try{f[p]=g(m)}catch(s){}}}c&&(_.Va=f);return f};_.O.U();
(0,_.M)("gadgets.util.getUrlParameters",_.O.U);

}catch(e){_._DumpException(e)}
try{
_.mb=window.gapi&&window.gapi.util||{};

}catch(e){_._DumpException(e)}
try{
_.mb.na=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^\w*:\/\//.test(a)||(a=window.location.href);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};


}catch(e){_._DumpException(e)}
try{
if(window.gapi&&window.gapi.rpc){_.ob=window.gapi.rpc;_.ob.call=_.ob.call;_.ob.N=_.ob.register;_.ob.Wb=_.ob.unregister;_.ob.wc=_.ob.setup;_.ob.ep=_.ob.sw;_.nb=_.ob}else{_.sb=function(a){if(a.f in{})return _.t;var c=a.t,f=_.pb[a.r],a=a.origin;return f&&(f.Ld===c||!f.Ld&&!c)&&(a===f.origin||"*"===f.origin)};_.wb=function(a,c,f){a=(0,_.tb)(a);_.ub[a.name]={Bm:c,qe:a.qe,mp:f||_.sb};(0,_.vb)()};_.zb=function(a){var c=a.c;if(!c)return(0,_.v)();var f=a.r,g=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,
0);_.xb?a.unshift(f,g+"__cb",_.r,c):a.unshift(f,g+"__cb"+c,_.r);_.yb.apply(_.r,a)}};_.Gb=function(a,c,f,g){var h=_.Ab,k=_.Bb,m=_.pb[c],p=h,s=(0,_.Cb)(c);if(m&&".."!==c){if(s.eh){if(!(k=_.pb[c].Ho)){k=_.r;k=_.Db?_.Db.substring(1).split("/"):[_.Ab];p=k.length-1;for(c=window.parent;c!==window.top;){var u=c.parent;if(!p--){for(var w=_.r,A=u.frames.length,B=0;B<A;++B)u.frames[B]==c&&(w=B);k.unshift("{"+w+"}")}c=u}k="/"+k.join("/")}p=k}else p=h="..";k=m.Ld}m=p;if(g&&s){p=_.sb;if(s.eh)var p=s.id.split("/"),
H=p[p.length-1],I=s.origin,p=function(a){var c=a.origin;return a.f==H&&(I==c||"*"==I)};_.xb?_.Eb["_"+ ++_.Fb]=[g,p]:(0,_.wb)("__cb"+(0,window.String)(++_.Fb),g,p);g=_.Fb}else g=_.r;f={s:a,f:h,r:m,t:k,c:g,a:f};a=(0,_.tb)(a);f.s=a.name;f.g=a.qe;return f};_.Jb=function(a){var c=_.pb[a];if(c&&c.Ab){var f=c.Dh;c.Dh=[];if(_.Hb)f.length&&(f=(0,_.Gb)("_processBatch",a,[f]),_.Ib.send(a,_.N.stringify(f),c.origin));else for(;f.length;)_.Ib.send(a,_.N.stringify(f.shift()),c.origin)}};_.tb=function(a){return 0===
a.indexOf("legacy__")?{name:a.substring(8),qe:_.q}:{name:a,qe:_.t}};_.vb=function(){for(var a=0,c;c=_.Kb[a];++a){var f=c.Jd,g=f.s,h=_.ub[g]||_.ub["*"];if(h&&(_.Kb.splice(a,1),--a,f.origin=c.origin,c=(0,_.zb)(f),f.callback=c,h.mp(f))){if("__cb"!==g&&!!h.qe!=!!f.g)break;f=h.Bm.apply(f,f.a);f!==_.n&&c(f)}}};_.Cb=function(a){var c=_.t,a=a.split("|"),f=a[0];0<=f.indexOf("/")&&(c=_.q);return{id:f,origin:a[1]||"*",eh:c}};_.Nb=function(a,c){var f=(0,_.Cb)(a),a=f.id;if(!_.pb.hasOwnProperty(a)){var g=_.Bb,
h=_.r;f.eh?(g=_.r,h=f.origin):".."!==a?(g=window.document.getElementById(a).src,h=_.mb.na(g),g=(0,_.Lb)(g).rpctoken):h=_.mb.na(_.Mb);f.origin&&(h=f.origin);_.pb[a]={Ld:g,Dh:[],origin:h,Ho:c,ak:function(){var c=a;_.pb[c].Ab=1;(0,_.Jb)(c)}};_.Ib.wc(a,_.pb[a].ak)}return _.pb[a].ak};_.Ob=function(){return"function"===typeof window.postMessage||"object"===typeof window.postMessage};_.yb=function(a,c,f,g){a=a||"..";(0,_.Nb)(a);var a=a.split("|",1)[0],h=[].slice.call(arguments,3),h=(0,_.Gb)(c,a,h,f);_.pb[a].Dh.push(h);
var k=a;_.Pb[k]||(_.Pb[k]=window.setTimeout(function(){_.Pb[k]=_.t;(0,_.Jb)(k)},0))};_.Qb={call:_.yb,N:_.wb,Wb:function(a){delete _.ub[(0,_.tb)(a).name]},wc:_.Nb,ep:_.Ob};if((0,_.Ob)()){_.Hb=_.t;_.Fb=0;_.Kb=[];_.pb={};_.ub={};_.Lb=_.O.U;_.Rb=(0,_.Lb)();_.Bb=_.Rb.rpctoken;_.Mb=_.Rb.parent||window.document.referrer;_.Ab=window!==window.top&&window.name||"..";_.Db=_.r;_.Pb={};_.Sb={vm:function(a,c){var f=_.N.parse(a);_.Kb.push({Jd:f,origin:c});(0,_.vb)()},cn:function(a){var c=window;"/"==a.charAt(0)&&
(a=a.substring(1),c=window.top);for(a=a.split("/");a.length;){var f;f=a.shift();"{"==f.charAt(0)&&"}"==f.charAt(f.length-1)&&(f=f.substring(1,f.length-1));if(".."===f)c=c.parent;else if(".."!==f&&c.frames[f])c=c.frames[f],"postMessage"in c||(0,_.l)("Not a window");else return _.r}return c},b:_.Ab,Gg:function(a){return(a=_.pb[a])&&a.Ld},d:function(a){_.Db=a}};_.Tb=function(a){a=_.N.parse(a);return a!=_.r&&"object"===typeof a&&!!a.g};_.Vb=function(a){var c=(0,window.String)(a.data),f=0!==c.indexOf("!_");
f||(c=c.substring(2));var g=(0,_.Tb)(c);if(f==g){if(!g&&(f=_.r,0==c.indexOf("{h:'")&&c.indexOf("'}")==c.length-2&&(f=(0,window.unescape)(c.substring(4,c.length-2))),f)){if(_.Ub[f])_.Ub[f]();return}var h=a.origin;window.setTimeout(function(){_.Sb.vm(c,h)},0)}};_.Ub={};_.Wb=_.r;(_.Wb=window.addEventListener)?(0,_.Wb)("message",_.Vb,_.t):(_.Wb=window.attachEvent)&&(0,_.Wb)("onmessage",_.Vb);window.___jsl=window.___jsl||{};_.Xb=window.___jsl;_.Xb.RPMQ=_.Xb.RPMQ||[];_.Xb.RPMQ.push(_.Vb);if(window!==window.parent){_.Yb=
window.parent;_.$b="{h:'"+(0,window.escape)(window.name)+"'}";_.ac=(0,_.Tb)(_.$b)?"":"!_";_.Yb.postMessage(_.ac+_.$b,"*")}_.Ib={wc:function(a,c){".."==a?c():_.Ub[a]=c},send:function(a,c,f){var a=_.Sb.cn(a),g=(0,_.Tb)(c)?"":"!_";a.postMessage(g+c,f)}};_.Eb={};_.xb=_.q;(0,_.wb)("__cb",function(a,c){var f=_.Eb["_"+a];f&&f[1](this)&&f[0].call(this,c)},(0,_.y)(_.q));(0,_.wb)("_processBatch",function(a){for(;a.length;){var c=a.shift();_.Kb.push({Jd:c,origin:this.origin})}(0,_.vb)()},(0,_.y)(_.q));(0,_.Nb)("..")}_.nb= _.Qb}_.bc=_.nb;


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.ec=_.ec||{};_.ec.lk=_.r;_.ec.Gj=_.r;_.ec.bf=_.r;_.ec.frameElement=_.r;_.ec=_.ec||{};
if(!_.ec.Uh){_.hc=function(a){var c=_.N.parse(a.data);if(c&&c.f){var f=_.Q.Ob(c.f);(!_.fc||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.gc)(c,a.origin)}};_.fc=_.q;_.ec.Uh={Hi:(0,_.y)("wpm"),b:(0,_.y)(_.q),S:function(a,c){_.kb.N("rpc",_.r,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.fc=_.t});_.gc=a;_.ic=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.hc,_.t):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.hc);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.hc);(0,_.ic)("..",_.q);return _.q},wc:function(a){(0,_.ic)(a,_.q);return _.q},call:function(a,c,f){var g=_.Q.Ob(a),h=_.Q.ii(a);g?window.setTimeout(function(){h.postMessage(_.N.stringify(f),g)},0):".."!=a&&(0,_.Ia)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.q}}};
_.ec=_.ec||{};
if(!_.ec.Qe){_.jc=_.ec;_.mc=function(a,c){function f(){a.apply({},arguments)}_.kc[c]=_.kc[c]||f;return _.lc+"."+c};_.tc=function(){if(_.nc===_.r&&window.document.body&&_.oc){var a=_.oc+"?cb="+window.Math.random()+"&origin="+_.pc+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.qc+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.nc=c.firstChild}++_.rc;_.sc!==_.r&&(_.nc!==_.r||50<=_.rc)?window.clearTimeout(_.sc):_.sc=window.setTimeout(_.tc,100)};_.zc=function(){_.vc[".."]||((0,_.wc)(".."),_.xc++,50<=_.xc&&_.yc!==_.r?(window.clearTimeout(_.yc),_.yc=_.r):_.yc=window.setTimeout(_.zc,100))};_.Bc=function(){if(_.nc!==_.r&&_.nc.setup)for(;0<_.Ac.length;){var a=_.Ac.shift(),c=a.gp;_.nc.setup(a.Ld,".."===c?_.Q.Of:c,".."===c?"INNER":"OUTER")}_.sc!==
_.r&&window.clearTimeout(_.sc);_.sc=_.r};_.Cc=function(){!_.vc[".."]&&_.yc===_.r&&(_.yc=window.setTimeout(_.zc,100))};_.Dc=function(a,c,f){var c=_.Q.Ob(a),g=_.Q.Mb(a);_.nc["sendMessage_"+(".."===a?_.Q.Of:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.nc,_.N.stringify(f),c);return _.q};_.Gc=function(a,c){var f=_.N.parse(a),g=f._scr;g?((0,_.Ec)(g,_.q),_.vc[g]=_.q,".."!==g&&(0,_.wc)(g,_.q)):window.setTimeout(function(){(0,_.Fc)(f,c)},0)};_.wc=function(a,c){var f=_.Q.Of,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.Dc)(a,f,g)};_.qc="___xpcswf";_.oc=_.r;_.Hc=_.t;_.Fc=_.r;_.Ec=_.r;_.nc=_.r;_.Ac=[];_.sc=_.r;_.rc=0;_.xc=0;_.yc=_.r;_.vc={};_.pc=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.Ic=window.___jsl._fm={};_.lc="___jsl._fm";_.kc=_.Ic;_.kb.N("rpc",_.r,function(a){_.Hc&&(_.oc=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.mc)(_.Bc,"ready");(0,_.mc)(_.Cc,"setupDone");(0,_.mc)(_.Gc,"receiveMessage");_.jc.Qe={Hi:(0,_.y)("flash"),b:(0,_.y)(_.q), S:function(a,c){_.Fc=a;_.Ec=c;return _.Hc=_.q},wc:function(a,c){_.Ac.push({Ld:c,gp:a});_.nc===_.r&&_.sc===_.r&&(_.sc=window.setTimeout(_.tc,100));return _.q},call:_.Dc,Xl:_.Gc,d:_.Bc,i:_.Cc}};
if(!window.gadgets||!window.gadgets.rpc){_.Oc=function(a,c){if(!_.Jc[a]){var f=_.Kc;c||(f=_.Lc);_.Jc[a]=f;for(var g=_.Mc[a]||[],h=0;h<g.length;++h){var k=g[h];k.t=_.Nc[a];f.call(a,k.f,k)}_.Mc[a]=[]}};_.Tc=function(a,c,f,g,h){function k(){_.Pc=_.q}if(!_.Nc[c]||_.Nc[c]!==f)(0,_.Ia)("Invalid auth token. "+_.Nc[c]+" vs "+f),(0,_.Qc)(c,2);h.onunload=function(){_.Rc[c]&&!_.Pc&&((0,_.Qc)(c,1),_.Q.Gd(c))};_.Sc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",k,_.t):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",k),_.Sc=_.q);g=_.N.parse((0,window.decodeURIComponent)(g))};_.Wc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.Nc[a.f]&&_.Nc[a.f]!==a.t&&((0,_.Ia)("Invalid auth token. "+_.Nc[a.f]+" vs "+a.t),(0,_.Qc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.Oc)(a.f,_.q)},0);else{a.c&&(a.callback=function(c){_.Q.call(a.f,(a.g?"legacy__":"")+"__cb",_.r,a.c,c)});if(c){var f=(0,_.Uc)(c);a.origin=
c;var g=a.r;if(!g||(0,_.Uc)(g)!=f)g=c;a.referer=g}f=(_.Vc[a.s]||_.Vc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.Q.call(a.f,"__cb",_.r,a.c,f)}};_.Uc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));var a=a.substring(0,a.indexOf("://")),f="",g=c.indexOf(":");if(-1!=g){var h=c.substring(g+
1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.Xc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.r}}return _.r};_.Yc=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.Xc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:_.r};
_.Zc=function(a,c){if(_.Rc[a]!==_.q){"undefined"===typeof _.Rc[a]&&(_.Rc[a]=0);var f=(0,_.Yc)(a);(".."===a||f!=_.r)&&_.Kc.wc(a,c)===_.q?_.Rc[a]=_.q:_.Rc[a]!==_.q&&10>_.Rc[a]++?window.setTimeout(function(){(0,_.Zc)(a,c)},500):(_.Jc[a]=_.Lc,_.Rc[a]=_.q)}};_.ad=function(a){(a=_.$c[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.cd=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.$c[a]=c;"undefined"!==typeof f&&(_.bd[a]=!!f)};_.dd=function(a,c){c=c||"";_.Nc[a]=(0,window.String)(c);(0,_.Zc)(a,c)};_.gd=function(a){a=(a.passReferrer||"").split(":",2);_.ed=a[0]||"none";_.fd=a[1]||"origin"};_.hd=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.Kc=_.ec.bf||_.Lc,_.Kc.S(_.Wc,_.Oc))};_.jd=
function(a,c,f){if(".."===a){var g=f||_.id.rpctoken||_.id.ifpctok||"",a=function(a){a=a&&a.rpc||{};(0,_.gd)(a);var f=a.parentRelayUrl||"",f=(0,_.Uc)(_.id.parent||c)+f;(0,_.cd)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.hd)(a);(0,_.dd)("..",g)};!_.id.parent&&c?a({}):_.kb.N("rpc",_.r,a)}else a:{var h=_.r;if("/"!=a.charAt(0)){if(!_.O)break a;(h=window.document.getElementById(a))||(0,_.l)((0,window.Error)("g`"+a))}var h=h&&h.src,k=c||_.Q.na(h);(0,_.cd)(a,k);h=_.O.U(h);(0,_.dd)(a,f||
h.rpctoken)}};_.Vc={};_.$c={};_.bd={};_.Nc={};_.kd=0;_.ld={};_.Rc={};_.id={};_.Jc={};_.Mc={};_.ed=_.r;_.fd=_.r;_.md=window.top!==window.self;_.nd=window.name;_.Qc=(0,_.v)();_.od=window.console;_.pd=_.od&&_.od.log&&function(a){_.od.log(a)}||(0,_.v)();_.qd=function(a){return function(){(0,_.pd)(a+": call ignored")}};_.Lc={getCode:(0,_.y)("noop"),isParentVerifiable:(0,_.y)(_.q),init:(0,_.qd)("init"),setup:(0,_.qd)("setup"),call:(0,_.qd)("call")};_.O&&(_.id=_.O.U());_.Pc=_.t;_.Sc=_.t;_.Kc=function(){if("flash"==
_.id.rpctx)return _.ec.Qe;if("rmr"==_.id.rpctx)return _.ec.lk;var a="function"===typeof window.postMessage?_.ec.Uh:"object"===typeof window.postMessage?_.ec.Uh:window.ActiveXObject?_.ec.Qe?_.ec.Qe:_.ec.Gj?_.ec.Gj:_.ec.bf:0<window.navigator.userAgent.indexOf("WebKit")?_.ec.lk:"Gecko"===window.navigator.product?_.ec.frameElement:_.ec.bf;a||(a=_.Lc);return a}();_.Vc[""]=function(){(0,_.pd)("Unknown RPC service: "+this.s)};_.Vc.__cb=function(a,c){var f=_.ld[a];f&&(delete _.ld[a],f.call(this,c))};_.Q=
{ga:function(a){"function"===typeof a.Lo&&(_.Qc=a.Lo)},N:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("h"));""===a&&(0,_.l)((0,window.Error)("i"));_.Vc[a]=c},Wb:function(a){("__cb"===a||"__ack"===a)&&(0,_.l)((0,window.Error)("j"));""===a&&(0,_.l)((0,window.Error)("k"));delete _.Vc[a]},we:function(a){_.Vc[""]=a},Ee:function(){delete _.Vc[""]},Zd:(0,_.v)(),call:function(a,c,f,g){var a=a||"..",h="..";".."===a?h=_.nd:"/"==a.charAt(0)&&(h=_.Q.na(window.location.href),h="/"+_.nd+(h?
"|"+h:""));++_.kd;f&&(_.ld[_.kd]=f);var k={s:c,f:h,c:f?_.kd:0,a:window.Array.prototype.slice.call(arguments,3),t:_.Nc[a],l:!!_.bd[a]},m;a:if("bidir"===_.ed||"c2p"===_.ed&&".."===a||"p2c"===_.ed&&".."!==a){m=window.location.href;var p="?";if("query"===_.fd)p="#";else if("hash"===_.fd)break a;p=m.lastIndexOf(p);p=-1===p?m.length:p;m=m.substring(0,p)}else m=_.r;m&&(k.r=m);".."!==a&&(0,_.Xc)(a)==_.r&&!window.document.getElementById(a)||(m=_.Jc[a],!m&&(0,_.Xc)(a)!==_.r&&(m=_.Kc),0===c.indexOf("legacy__")&&
(m=_.Kc,k.s=c.substring(8),k.c=k.c?k.c:_.kd),k.g=_.q,k.r=h,m?(_.bd[a]&&(m=_.ec.bf),m.call(a,h,k)===_.t&&(_.Jc[a]=_.Lc,_.Kc.call(a,h,k))):_.Mc[a]?_.Mc[a].push(k):_.Mc[a]=[k])},de:_.ad,Wc:_.cd,Vc:_.dd,xc:_.jd,Mb:function(a){return _.Nc[a]},Gd:function(a){delete _.$c[a];delete _.bd[a];delete _.Nc[a];delete _.Rc[a];delete _.Jc[a]},ce:function(){return _.Kc.Hi()},ue:function(a,c){4<a.length?_.Kc.Xl(a,_.Wc):_.Tc.apply(_.r,a.concat(c))},ve:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.Wc)(a)},
0)},na:_.Uc,Ob:function(a){var c=_.r,c=(0,_.ad)(a);c||(c=(c=(0,_.Xc)(a))?c.origin:".."==a?_.id.parent:window.document.getElementById(a).src);return(0,_.Uc)(c)},S:function(){_.Kc.S(_.Wc,_.Oc)===_.t&&(_.Kc=_.Lc);_.md?(0,_.jd)(".."):_.kb.N("rpc",_.r,function(a){a=a.rpc||{};(0,_.gd)(a);(0,_.hd)(a)})},ii:_.Yc,Wl:_.Xc,b:"__ack",Of:_.nd||"..",j:0,i:1,d:2};_.Q.S()}else if("undefined"==typeof _.Q||!_.Q)_.Q=window.gadgets.rpc,_.Q.ga=_.Q.config,_.Q.N=_.Q.register,_.Q.Wb=_.Q.unregister,_.Q.we=_.Q.registerDefault,
_.Q.Ee=_.Q.unregisterDefault,_.Q.Zd=_.Q.forceParentVerifiable,_.Q.call=_.Q.call,_.Q.de=_.Q.getRelayUrl,_.Q.Wc=_.Q.setRelayUrl,_.Q.Vc=_.Q.setAuthToken,_.Q.xc=_.Q.setupReceiver,_.Q.Mb=_.Q.getAuthToken,_.Q.Gd=_.Q.removeReceiver,_.Q.ce=_.Q.getRelayChannel,_.Q.ue=_.Q.receive,_.Q.ve=_.Q.receiveSameDomain,_.Q.na=_.Q.getOrigin,_.Q.Ob=_.Q.getTargetOrigin,_.Q.ii=_.Q._getTargetWin,_.Q.Wl=_.Q._parseSiblingId;
(0,_.M)("gadgets.rpc.config",_.Q.ga);(0,_.M)("gadgets.rpc.register",_.Q.N);(0,_.M)("gadgets.rpc.unregister",_.Q.Wb);(0,_.M)("gadgets.rpc.registerDefault",_.Q.we);(0,_.M)("gadgets.rpc.unregisterDefault",_.Q.Ee);(0,_.M)("gadgets.rpc.forceParentVerifiable",_.Q.Zd);(0,_.M)("gadgets.rpc.call",_.Q.call);(0,_.M)("gadgets.rpc.getRelayUrl",_.Q.de);(0,_.M)("gadgets.rpc.setRelayUrl",_.Q.Wc);(0,_.M)("gadgets.rpc.setAuthToken",_.Q.Vc);(0,_.M)("gadgets.rpc.setupReceiver",_.Q.xc);
(0,_.M)("gadgets.rpc.getAuthToken",_.Q.Mb);(0,_.M)("gadgets.rpc.removeReceiver",_.Q.Gd);(0,_.M)("gadgets.rpc.getRelayChannel",_.Q.ce);(0,_.M)("gadgets.rpc.receive",_.Q.ue);(0,_.M)("gadgets.rpc.receiveSameDomain",_.Q.ve);(0,_.M)("gadgets.rpc.getOrigin",_.Q.na);(0,_.M)("gadgets.rpc.getTargetOrigin",_.Q.Ob);


}catch(e){_._DumpException(e)}
try{
_.rd=_.mb=_.mb||{};_.sd={Wh:"bsh",Zh:"h"};window.___jsl=window.___jsl||{};_.rd.Ud={Em:function(){return window.___jsl[_.sd.Wh]},Bg:function(){return window.___jsl[_.sd.Zh]},Cf:function(a){window.___jsl[_.sd.Wh]=a},So:function(a){window.___jsl[_.sd.Zh]=a}};


}catch(e){_._DumpException(e)}
try{
_.td=window.iframer=window.iframer||{};_.R=window.iframes=window.iframes||{};

}catch(e){_._DumpException(e)}
try{
_.ud=window.oauth2||{};

}catch(e){_._DumpException(e)}
try{
_.xd=function(a){var c=_.yd,f=(0,_.L)("googleapis.config/sessionIndex");f==_.r&&(f=window.__X_GOOG_AUTHUSER);if(f==_.r){var g=window.google;g&&(f=g.authuser)}f==_.r&&(a==_.r&&(a=window.location.href),f=a?c(a,"authuser"):_.r);return f==_.r?_.r:(0,window.String)(f)};_.yd=function(a,c){return(a?_.O.U((0,window.String)(a)):{})[c]||_.r};
_.zd=function(a,c,f){var g=(a=(0,window.String)(a))?_.O.U(a):{};if(g.authuser!=_.r||g.hd!=_.r)return a;c=(0,_.xd)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var k=h[1],m=h[4],p=h[5];h[3]=="/"+f&&(g=(k||"")+(m||"/")+(p||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return k=h[2],a=h[4]||h[5],p=h[6],c!=_.r&&(g=(k||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+(p||"")),g}f=c==
_.r?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.Ad=_.zd;

}catch(e){_._DumpException(e)}
try{
_.R.D=_.R.D||{};_.R.D.Xh="friendlyIframe";_.R.D.hm=function(a){try{return!!a.document}catch(c){}return _.t};_.R.D.jc=function(a){var c=a.parent;return a!=c&&_.R.D.hm(c)?_.R.D.jc(c):a};_.R.D.rj=function(a){try{return _.R.D.jc(a)!=a&&!!a.frameElement&&a.frameElement.name==_.R.D.Xh}catch(c){return _.t}};_.R.D.In=function(a){var c=a.userAgent||"",a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.Bd=window.ToolbarApi,_.Bd.ia=window.ToolbarApi.getInstance,_.Bd.prototype=window.ToolbarApi.prototype,_.C=_.Bd.prototype,_.C.Sj=_.Bd.prototype.openWindow,_.C.vi=_.Bd.prototype.closeWindow,_.C.vk=_.Bd.prototype.setOnCloseHandler,_.C.ti=_.Bd.prototype.canClosePopup,_.C.gk=_.Bd.prototype.resizeWindow;else{_.Cd=_.r;_.Bd=(0,_.v)();_.Bd.ia=function(){!_.Cd&&(window.external&&window.external.GTB_IsToolbar)&&(_.Cd=new _.Bd);return _.Cd};_.C=_.Bd.prototype;_.C.Sj=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.C.vi=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.C.vk=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.C.ti=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.C.gk=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.Bd;window.ToolbarApi.getInstance=_.Bd.ia};
if(!window.iframes||!window.iframes.open){_.Ed=/^[-_.0-9A-Za-z]+$/;_.Fd={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Gd={onBeforeParentOpen:"beforeparentopen"};_.Hd={longdesc:_.q,name:_.q,src:_.q,frameborder:_.q,marginwidth:_.q,marginheight:_.q,scrolling:_.q,align:_.q,height:_.q,width:_.q,id:_.q,"class":_.q,style:_.q,title:_.q,tabindex:_.q,hspace:_.q,vspace:_.q,allowtransparency:_.q};_.Id=
{onOpen:function(a){var c=a.ba();a.La(c.container||c.element);return a},onClose:function(a){a.remove()}};_.Jd=window.encodeURIComponent||window.escape;_.Kd=function(a){(0,_.Ia)(a.join(""))};_.Ld=function(){_.R.oj++;return["I",_.R.oj,"_",(new window.Date).getTime()].join("")};_.Md=function(a){var c={allowtransparency:"true",frameborder:0,hspace:0,marginheight:0,marginwidth:0,scrolling:"no",style:"",tabindex:"0",vspace:0,width:"100%"},f;for(f in a)a.hasOwnProperty(f)&&(c[f]=a[f]);return c};_.Od=function(a,
c,f){f=f||{};f.id||(f.id=a);f.name||(f.name=a);f.src||(f.src=c);a=(0,_.Md)(f);c=[];c.push("<iframe ");for(var g in a)a.hasOwnProperty(g)&&(_.Hd[g.toLowerCase()]?(f=(0,window.String)(a[g]),c.push(g),c.push('="'),c.push(_.O.Yd("style"==g.toLowerCase()?(0,_.Nd)(f):f)),c.push('" ')):(0,_.Kd)(['Iframe attribute "',g,'" not allowed.']));c.push("></iframe>");return c.join("")};_.Nd=function(a){if(!a)return"";for(var c=[],a=a.split(";"),f=0,g=a.length;f<g;++f){var h=a[f];0==h.length&&f+1==g||(h=h.split(":"),
2==h.length&&h[0].match(/^[ a-zA-Z_-]+$/)&&h[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?c.push(h.join(":")):(0,_.Kd)(['Iframe style "',a[f],'" not allowed.']))}return c.join(";")};_.Pd=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname;return c.substring(0,
c.lastIndexOf("/")+1)+a};_.Qd=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.N.stringify(a):a};_.Rd=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.r,g.gd=a):(g.hash=a.substring(h+1),g.gd=a.substring(0,h));a=g.gd.indexOf("?");-1==a?g.Ed=_.r:(g.Ed=g.gd.substring(a+1),g.gd=g.gd.substring(0,a));var a=f?g.hash?[g.hash]:[]:g.Ed?[g.Ed]:[],k;for(k in c)c.hasOwnProperty(k)&&(h=(0,_.Qd)(c[k]),a.push([(0,_.Jd)(k),(0,_.Jd)(h)].join("=")));f?g.hash=a.join("&"):
g.Ed=a.join("&");return g.gd+(g.Ed?"?"+g.Ed:"")+(g.hash?"#"+g.hash:"")};_.Sd=(0,_.v)();_.Td=function(){var a=(0,_.xd)();return a!==_.n&&a!==_.r&&""!==a?"u/"+a+"/":""};_.Ud=function(a){var c=_.O.U().jsh||_.mb.Ud.Bg();!a.jsh&&c&&(a.jsh=c);c=_.O.U()._bsh||_.mb.Ud.Em();!a._bsh&&c&&(a._bsh=c)};_.Vd=function(a){a&&a.match(_.Ed)&&(0,_.Ba)("googleapis.config/gcv",a)};_.Wd=function(a){_.mb.Ud.So(a)};_.Xd=function(a){_.mb.Ud.Cf(a)};_.Yd=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);
return f};_.Zd=function(a){_.R.yf[a]||(_.R.yf[a]={},_.Q.N(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,k=_.R.yf[a][g],m;k&&window.Object.hasOwnProperty.call(k,c)?m=k[c]:window.Object.hasOwnProperty.call(_.R.td,a)&&(m=_.R.td[a]);if(m)return g=window.Array.prototype.slice.call(arguments,1),m._iframe_wrapped_rpc_&&h&&g.push(h),m.apply({},g)}(0,_.Kd)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,
'".']);return _.r}));return _.R.yf[a]};_.$d=function(a,c,f,g,h){var k=[],m;for(m in a)if(a.hasOwnProperty(m)){var p=c,s=f,u=a[m],w=g,A=(0,_.Zd)(m);A[p]=A[p]||{};w=_.O.yd(w,u);u._iframe_wrapped_rpc_&&(w._iframe_wrapped_rpc_=_.q);A[p][s]=w;k.push(m)}if(h)for(m in _.R.td)_.R.td.hasOwnProperty(m)&&k.push(m);return k.join(",")};_.ae=function(a,c,f){function g(g){var k=window.Array.prototype.slice.call(arguments,0),m=k[k.length-1];if("function"===typeof m){var p=m;k.pop()}k.unshift(c,a,p,f);var s;a:if(".."==
c||window.document.getElementById(c))s=window;else{for(m=0;m<_.R.sg.length;m++)try{var u=_.R.sg[m];if(u&&u.document&&(u.document||window.document).getElementById(c)){s=u;break a}}catch(w){}s=_.r}s?s==window?_.Q.call.apply(_.Q,k):(s=s.gadgets.rpc,s.call.apply(s,k)):(0,_.Kd)(["RPC ",a,' not sent: target iframe "',c,'" not found.'])}g._iframe_wrapped_rpc_=_.q;return g};_.be=function(a,c,f){var g={};if(a&&a._methods)for(var a=a._methods.split(","),h=0;h<a.length;h++){var k=a[h];g[k]=(0,_.ae)(k,c,f)}return g};
_.ce=function(a){return a&&a.disableMultiLevelParentRelay?_.t:_.td&&_.td._open&&"inline"!=a.style&&a.inline!==_.q&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.de=function(a){a&&a.parentNode&&a.parentNode.removeChild(a)};_.ee=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};_.fe=function(a,c,f,g,h,k,m,p){if(":"==a.charAt(0)){var a="iframes/"+a.substring(1),s=
a+"/params",u={},w=(0,_.L)(s);(0,_.Ba)(s,w||u);s=a+"/url";u=(u=(0,_.L)(a+"/url"))||"";u=u.replace(/:session_prefix:/g,(0,_.Td)());u=u.replace(/:session_index:/g,(0,_.xd)()||"0");u=u.replace(/:socialhost:/g,(0,_.L)("iframes/:socialhost:"));(0,_.Ba)(s,(0,_.Pd)(u));a=(0,_.L)(a)}else a={url:(0,_.Pd)(a)};this.ga=a;this.openParams=this.o=c;this.pb=f||{};this.Va=g;this.i=_.t;this.Yn(c.style);this.d={};this.Sc(function(){this.Yl(h);k&&this.Uf("close",k)});this.Sb=this.ac=m;this.yh=(p||[]).slice();m&&this.yh.unshift(m.W())};
_.C=_.fe.prototype;_.C.ba=(0,_.x)("o");_.C.Oa=(0,_.x)("pb");_.C.Nb=(0,_.x)("Va");_.C.ya=(0,_.x)("Sb");_.C.Yn=function(a){if(!this.i)if(a=a&&!_.R.Be[a]&&_.R.gg[a]){this.j=[];var c=this;a(function(){c.i=_.q;for(var a=0,g=c.j.length;a<g;++a)c.j[a].call(c)})}else this.i=_.q};_.C.Sc=function(a){this.i?a.call(this):this.j.push(a)};_.C.Yl=function(a){var c=this.Lm();if(c){if("function"===typeof c)c=c(this);else{var f={},g;for(g in c){var h=c[g];f[g]="function"===typeof h?_.O.yd(c,h,this):h}c=f}for(var k in a)f=
c[k],"function"===typeof f&&this.Uf(a[k],_.O.yd(c,f))}};_.C.Y=function(a,c){this.Sc(function(){this.Uf(a,c)})};_.C.Uf=function(a,c){this.d[a]=this.d[a]||[];this.d[a].push(c)};_.C.Bb=function(a,c){this.Sc(function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};_.C.lb=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),k=0,m=g.length;k<m;++k)try{f=g[k].apply({},h)}catch(p){(0,_.Kd)(['Exception when calling callback "',
a,'" with exception "',p.name,": ",p.message,'".'])}return f};_.C.Lm=function(){var a=this.o.style;return a&&_.R.Be[a]?_.R.Be[a]:a?((0,_.Sa)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),_.r):_.Id};_.C.Ue=function(a){return"number"==typeof a?{value:a,Ec:a+"px"}:"100%"==a?{value:100,Ec:"100%",xj:_.q}:_.r};_.S=function(a,c,f,g,h,k,m){_.fe.call(this,a,c,f,g,_.Fd,h,k,m);this.id=c.id||(0,_.Ld)();this.lp=!!c.rpcToken;this.Fh=c.rpcToken||window.Math.round(1E9*(0,_.Za)());
var a=this.pb,c={},f=this.ga.params||{},p;for(p in a)"#"==p.charAt(0)&&(c[p.substring(1)]=a[p]),0==p.indexOf("fr-")&&(c[p.substring(3)]=a[p]),"#"==f[p]&&(c[p]=a[p]);for(var s in c)delete a["fr-"+s],delete a["#"+s],delete a[s];this.Jn=c;this.mg={};this.Sc(function(){this.lb("open");(0,_.Yd)(this.mg,this)})};(0,_.ee)(_.S,_.fe);_.C=_.S.prototype;_.C.La=function(a,c){if(!this.ga.url)return(0,_.Kd)(["Cannot open iframe, empty URL."]),this;var f=window.location.protocol+"//"+window.location.host,g=this.id;
(0,_.Ud)(this.pb);var h=(0,_.Yd)(this.Va);h._ready=this.qf;h._close=this.close;h._open=this.Tj;h._resizeMe=this.hk;h._renderstart=this.Pj;var k=this.Jn;k.id=g;k.parent=f;k.rpctoken=this.Fh;k._methods=(0,_.$d)(h,g,"",this,_.q);f=this.kp();f=(0,_.Rd)(f,k,_.q);a="string"===typeof a?window.document.getElementById(a):a;if(this.ba().allowPost&&2E3<f.length)this.to(a,g,k,c);else if(this.lp)a.innerHTML=(0,_.Od)(g,f,c);else if(_.R.D.In(window.navigator||{})){a.innerHTML=(0,_.Od)(g,"about:blank",c);a.firstChild.src=
f;try{a.firstChild.contentDocument.location.href=f}catch(m){}}else{k=(0,_.Od)(g,f,c);try{a.innerHTML=k}catch(p){h=window.document.createElement("div");for(h.innerHTML=k;a.firstChild;)a.removeChild(a.firstChild);a.appendChild(h.firstChild)}}this.Cc=a;this.mb=a.firstChild;_.R.Nc[g]=this;_.Q.Vc(g,this.Fh);_.Q.Wc(g,f);return this};_.C.dm=function(a){var c=a.id,f=a.src,g=/#(?:.*&)?rpctoken=(\d+)/.exec(f),g=g&&g[1];this.id=c;this.Fh=g;this.Cc=a.parentNode;this.mb=a;_.R.Nc[c]=this;a=(0,_.Yd)(this.Va);a._ready=
this.qf;a._close=this.close;a._open=this.Tj;a._resizeMe=this.hk;a._renderstart=this.Pj;(0,_.$d)(a,c,"",this,_.q);_.Q.Vc(c,g);_.Q.Wc(c,f);return this};_.C.cm=function(a){var a=(0,_.Md)(a||{}),c;for(c in a)window.Object.prototype.hasOwnProperty.call(a,c)&&("style"==c?this.mb.style.cssText=a[c]:this.mb.setAttribute(c,a[c]))};_.C.to=function(a,c,f,g){a.innerHTML=(0,_.Od)(c,"",g);var h;-1!=window.navigator.userAgent.indexOf("WebKit")&&(h=a.firstChild,g=(0,_.Od)(c+"_inner","",{style:"display:none"}),h=
h.contentWindow.document,h.open(),h.write(g));g=(0,_.Rd)(this.ga.url,f,_.q);f=this.pb||{};g={action:g,method:"POST",target:c};c=window.document.createElement("form");c.style.display="none";for(var k in g)g.hasOwnProperty(k)&&(c[k]=g[k]);for(var m in f)f.hasOwnProperty(m)&&(k=window.document.createElement("input"),k.type="hidden",k.name=m,k.value=f[m],c.appendChild(k));a.appendChild(c);c.submit();c.parentNode.removeChild(c);h&&h.close()};_.C.Sa=function(a,c){this.mg[a]=c};_.C.W=(0,_.x)("id");_.C.ca=
(0,_.x)("mb");_.C.Q=(0,_.x)("Cc");_.C.Eb=(0,_.ba)("Cc");_.C.qf=function(a){var c=(0,_.be)(a,this.id,"");this.Sb&&"function"==typeof this.Va._ready&&(a._methods=(0,_.$d)(c,this.Sb.W(),this.id,this,_.t),this.Va._ready(a));(0,_.Yd)(a,this);(0,_.Yd)(c,this);this.lb("ready",a)};_.C.Pj=function(a){this.lb("renderstart",a)};_.C.zo=function(a,c,f){f._methods=(0,_.$d)((0,_.be)(f,a,""),this.id,a,this,_.t);c(f)};_.C.close=function(a){a=this.lb("close",a);if(_.R.D.rj(window)){var c=window.frameElement,f=c.parentNode;
"friendlyIframeContainer"==f.className?(0,_.de)(f):(0,_.de)(c)}delete _.R.Nc[this.id];return a};_.C.remove=function(){(0,_.de)(window.document.getElementById(this.id))};_.C.Tj=function(a){var c=(0,_.be)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.Cc);if((0,_.ce)(a.openParams))new _.ge(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else if("expandable"===a.openParams.style&&a.openParams.inline!==_.q&&_.R.D.jc(window)!=
window)this.ro(a,c);else{var f=new _.S(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;f.Sc(function(){var a=g.qi(f);c._onopen(a)})}};_.C.ro=function(a,c){var f=_.R.D.jc(window),g={height:0,name:_.R.D.Xh,style:"left:0;position:absolute;top:0;z-index:-10000",width:0},h=f.document.createElement("ins");h.className="friendlyIframeContainer";h.innerHTML=(0,_.Od)("","about:blank",g);f.document.body.appendChild(h);f=h.firstChild.contentWindow;_.R.sg.push(f);g=f.document;h=['<html><body><script src="',
_.R.yg(),'"><\/script></body></html>'].join("");g.open();g.write(h);g.close();g=a.openParams.id||(0,_.Ld)();a.openParams.id=g;g=_.O.yd(this,this.zo,g,c._ready);c._ready=g;var k=_.O.yd(f,function(f,g){if(!f.le||"function"!=typeof f.le.open)return _.t;var h=f.le.open(a.url,a.openParams,a.params,c,c._onclose,g),h=g.qi(h);c._onopen(h);return _.q},f,this),m=window.setInterval(function(){k()&&window.clearInterval(m)},10)};_.C.qi=function(a){var c={childId:a.W()},f=a.mg;f._toclose=a.close;c._methods=(0,_.$d)(f,
this.id,a.id,a,_.t);return c};_.C.hk=function(a){if(this.lb("resize",a)===_.n&&this.mb){var c=this.Ue(a.width);c!=_.r&&(this.mb.style.width=c.Ec);a=this.Ue(a.height);a!=_.r&&(this.mb.style.height=a.Ec);if(this.mb.parentElement&&(c!=_.r&&c.xj||a!=_.r&&a.xj))this.mb.parentElement.style.display="block"}};_.C.kp=function(){return(0,_.Rd)(this.ga.url,this.pb,_.t)};_.ge=function(a,c,f,g,h,k,m){_.fe.call(this,a,c,f,g,_.Gd,h,k,m);this.url=a;this.b=_.r;this.G=(0,_.Ld)();this.Sc(function(){this.lb("beforeparentopen");
var a=(0,_.Yd)(this.Va);a._onopen=this.J;a._ready=this.qf;a._onclose=this.F;this.pb._methods=(0,_.$d)(a,"..",this.G,this,_.q);var a={},c;for(c in this.pb)a[c]=(0,_.Qd)(this.pb[c]);_.td._open({url:this.ga.url,openParams:this.o,params:a,proxyId:this.G,openedByProxyChain:this.yh})})};(0,_.ee)(_.ge,_.fe);_.ge.prototype.Ki=(0,_.x)("b");_.ge.prototype.J=function(a){this.b=a.childId;var c=(0,_.be)(a,"..",this.b);(0,_.Yd)(c,this);this.close=c._toclose;_.R.Nc[this.b]=this;this.Sb&&this.Va._onopen&&(a._methods=
(0,_.$d)(c,this.Sb.W(),this.b,this,_.t),this.Va._onopen(a))};_.ge.prototype.qf=function(a){var c=(0,window.String)(this.b),f=(0,_.be)(a,"..",c);(0,_.Yd)(a,this);(0,_.Yd)(f,this);this.lb("ready",a);this.Sb&&this.Va._ready&&(a._methods=(0,_.$d)(f,this.Sb.W(),c,this,_.t),this.Va._ready(a))};_.ge.prototype.F=function(a){if(this.Sb&&this.Va._onclose)this.Va._onclose(a);else return a=this.lb("close",a),delete _.R.Nc[this.b],a};_.he=function(a,c,f,g,h,k,m){_.fe.call(this,a,c,f,g,_.Gd,k,m);this.X=h;g._close=
this.close;this.onClosed=this.b;this.z=0;this.Sc(function(){this.lb("beforeparentopen");var a=(0,_.Yd)(this.Va);this.pb._methods=(0,_.$d)(a,"..",this.G,this,_.q);(0,_.Ud)(this.pb);var a=(0,_.Rd)(this.ga.url,this.pb,_.t),c=h.Sj(a);this.canAutoClose=function(a){a(h.ti(c))};h.vk(c,this);this.z=c})};(0,_.ee)(_.he,_.fe);_.he.prototype.close=function(a){a=this.lb("close",a);this.X.vi(this.z);return a};_.he.prototype.b=function(){this.lb("close")};_.ie=function(a){return _.R.Be[a]};_.je=function(a,c){_.R.Be[a]=
c};_.ke=function(a){a=a||{};"auto"===a.height&&(a.height=_.Wa.zg());var c=window&&_.Bd&&_.Bd.ia();c?c.gk(a.width||0,a.height||0):_.td&&_.td._resizeMe&&_.td._resizeMe(a)};_.me=function(a){(0,_.Vd)(a)};_.Dd=function(){function a(a){var c=_.t;try{if(a!=_.r)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.td.id)}catch(m){}try{_.R.tf={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.R.sf.length;++a)_.R.sf[a](_.R.tf);
_.R.sf=[]}catch(p){}}_.R.Nc={};_.R.Be={};_.R.gg={};_.R.oj=0;_.R.sg=[];_.R.yf={};_.R.td={};_.R.tf=_.r;_.R.sf=[];_.Q.N("_noop_echo",function(){var a=_.R.Nc[this.f],c=a&&a.Sb,f=_.r;c&&(f={},f.id=c.W(),f.proxyChain=a.yh);this.callback(f)});if(window.parent!=window){var c=_.O.U();c.gcv&&(0,_.Vd)(c.gcv);var f=c.jsh;f&&(0,_.Wd)(f);(0,_.Yd)((0,_.be)(c,"..",""),_.td);(0,_.Yd)(c,_.td);window.setTimeout(function(){_.Q.call("..","_noop_echo",a)},0)}_.R.aa=_.ie;_.R.ka=_.je;_.R.rk=_.me;_.R.Vb=_.ke;_.R.Ii=function(a){return _.R.gg[a]};
_.R.Df=function(a,c){_.R.gg[a]=c};_.R.fk=_.ke;_.R.Ak=_.me;_.R.Rb={};_.R.Rb.get=_.ie;_.R.Rb.set=_.je;_.R.ji=function(a,c){(0,_.Zd)(a);_.R.td[a]=c||window[a]};_.R.gq=function(a){delete _.R.td[a]};_.R.open=function(a,c,f,m,p,s){3==arguments.length?m={}:4==arguments.length&&"function"===typeof m&&(p=m,m={});var u="bubble"===c.style&&_.Bd&&_.Bd.ia();return u?new _.he(a,c,f,m,u,p,s):(0,_.ce)(c)?new _.ge(a,c,f,m,p,s):new _.S(a,c,f,m,p,s)};_.R.close=function(a,c){_.td&&_.td._close&&_.td._close(a,c)};_.R.Ab=
function(a,c,f){2==arguments.length&&"function"===typeof p&&(f=c,c={});var m=a||{};"height"in m||(m.height=_.Wa.zg());var p=c||{};m._methods=(0,_.$d)(p,"..","",_.td,_.q);_.td&&_.td._ready&&_.td._ready(m,f)};_.R.Cg=function(a){_.R.tf?a(_.R.tf):_.R.sf.push(a)};_.R.ri=function(a,c,f){var m=window.Array.prototype.slice.call(arguments);_.R.Cg(function(a){a.sameOrigin&&(m.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.Q.call.apply(_.Q,m))})};_.R.Uj=function(a){return!!_.R.Nc[a]};
_.R.yg=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.L)("googleapis.config/gcv")].join("")};_.R.Zj=function(a){var c={mouseover:1,mouseout:1};if(_.td._event)for(var f=0;f<a.length;f++){var m=a[f];m in c&&_.O.Sd(window.document,m,function(a){_.td._event({event:a.type,timestamp:(new window.Date).getTime()})},_.q)}};_.R.tk=_.Wd;_.R.Cf=_.Xd;_.R.Zn=_.Sd;_.R.qj=_.td};(0,_.Dd)()}else _.R.ji=_.R.allow,_.R.ri=_.R.callSiblingOpener,_.R.close=_.R.close,_.R.yg=_.R.getGoogleConnectJsUri,_.R.aa=_.R.getHandler,
_.R.Ii=_.R.getDeferredHandler,_.R.Cg=_.R.getParentInfo,_.R.qj=_.R.iframer,_.R.open=_.R.open,_.R.Uj=_.R.openedId_,_.R.Zj=_.R.propagate,_.R.Ab=_.R.ready,_.R.Vb=_.R.resize,_.R.rk=_.R.setGoogleConnectJsVersion,_.R.tk=_.R.setJsHint,_.R.Cf=_.R.setBootstrapHint,_.R.ka=_.R.setHandler,_.R.Df=_.R.setDeferredHandler,_.fe=window.IframeBase,_.fe.prototype=window.IframeBase.prototype,_.C=_.fe.prototype,_.C.Y=_.fe.prototype.addCallback,_.C.Nb=_.fe.prototype.getMethods,_.C.ya=_.fe.prototype.getOpenerIframe,_.C.ba=
_.fe.prototype.getOpenParams,_.C.Oa=_.fe.prototype.getParams,_.C.Bb=_.fe.prototype.removeCallback,_.S=window.Iframe,_.S.prototype=window.Iframe.prototype,_.C=_.S.prototype,_.C.close=_.S.prototype.close,_.C.Sa=_.S.prototype.exposeMethod,_.C.W=_.S.prototype.getId,_.C.ca=_.S.prototype.getIframeEl,_.C.Q=_.S.prototype.getSiteEl,_.C.La=_.S.prototype.openInto,_.C.remove=_.S.prototype.remove,_.C.Eb=_.S.prototype.setSiteEl,_.C.Y=_.S.prototype.addCallback,_.C.Nb=_.S.prototype.getMethods,_.C.ya=_.S.prototype.getOpenerIframe,
_.C.ba=_.S.prototype.getOpenParams,_.C.Oa=_.S.prototype.getParams,_.C.Bb=_.S.prototype.removeCallback,_.ge=window.IframeProxy,_.ge.prototype=window.IframeProxy.prototype,_.C=_.ge.prototype,_.C.Ki=_.ge.prototype.getTargetIframeId,_.C.Y=_.ge.prototype.addCallback,_.C.Nb=_.ge.prototype.getMethods,_.C.ya=_.ge.prototype.getOpenerIframe,_.C.ba=_.ge.prototype.getOpenParams,_.C.Oa=_.ge.prototype.getParams,_.C.Bb=_.ge.prototype.removeCallback,window.IframeWindow&&(_.he=window.IframeWindow,_.he.prototype=window.IframeWindow.prototype, _.he.prototype.close=_.he.prototype.close,_.he.prototype.b=_.he.prototype.onClosed),_.R.Rb=window.iframes.handlers,_.R.Rb.get=_.R.Rb.get,_.R.Rb.set=_.R.Rb.set,_.R.fk=_.R.resizeMe,_.R.Ak=_.R.setVersionOverride;
(0,_.M)("iframes.allow",_.R.ji);(0,_.M)("iframes.callSiblingOpener",_.R.ri);(0,_.M)("iframes.close",_.R.close);(0,_.M)("iframes.getGoogleConnectJsUri",_.R.yg);(0,_.M)("iframes.getHandler",_.R.aa);(0,_.M)("iframes.getDeferredHandler",_.R.Ii);(0,_.M)("iframes.getParentInfo",_.R.Cg);(0,_.M)("iframes.iframer",_.R.qj);(0,_.M)("iframes.open",_.R.open);(0,_.M)("iframes.openedId_",_.R.Uj);(0,_.M)("iframes.propagate",_.R.Zj);(0,_.M)("iframes.ready",_.R.Ab);(0,_.M)("iframes.resize",_.R.Vb);
(0,_.M)("iframes.setGoogleConnectJsVersion",_.R.rk);(0,_.M)("iframes.setBootstrapHint",_.R.Cf);(0,_.M)("iframes.setJsHint",_.R.tk);(0,_.M)("iframes.setHandler",_.R.ka);(0,_.M)("iframes.setDeferredHandler",_.R.Df);(0,_.M)("IframeBase",_.fe);(0,_.M)("IframeBase.prototype.addCallback",_.fe.prototype.Y);(0,_.M)("IframeBase.prototype.getMethods",_.fe.prototype.Nb);(0,_.M)("IframeBase.prototype.getOpenerIframe",_.fe.prototype.ya);(0,_.M)("IframeBase.prototype.getOpenParams",_.fe.prototype.ba);
(0,_.M)("IframeBase.prototype.getParams",_.fe.prototype.Oa);(0,_.M)("IframeBase.prototype.removeCallback",_.fe.prototype.Bb);(0,_.M)("Iframe",_.S);(0,_.M)("Iframe.prototype.close",_.S.prototype.close);(0,_.M)("Iframe.prototype.exposeMethod",_.S.prototype.Sa);(0,_.M)("Iframe.prototype.getId",_.S.prototype.W);(0,_.M)("Iframe.prototype.getIframeEl",_.S.prototype.ca);(0,_.M)("Iframe.prototype.getSiteEl",_.S.prototype.Q);(0,_.M)("Iframe.prototype.openInto",_.S.prototype.La);
(0,_.M)("Iframe.prototype.remove",_.S.prototype.remove);(0,_.M)("Iframe.prototype.setSiteEl",_.S.prototype.Eb);(0,_.M)("Iframe.prototype.addCallback",_.S.prototype.Y);(0,_.M)("Iframe.prototype.getMethods",_.S.prototype.Nb);(0,_.M)("Iframe.prototype.getOpenerIframe",_.S.prototype.ya);(0,_.M)("Iframe.prototype.getOpenParams",_.S.prototype.ba);(0,_.M)("Iframe.prototype.getParams",_.S.prototype.Oa);(0,_.M)("Iframe.prototype.removeCallback",_.S.prototype.Bb);(0,_.M)("IframeProxy",_.ge);
(0,_.M)("IframeProxy.prototype.getTargetIframeId",_.ge.prototype.Ki);(0,_.M)("IframeProxy.prototype.addCallback",_.ge.prototype.Y);(0,_.M)("IframeProxy.prototype.getMethods",_.ge.prototype.Nb);(0,_.M)("IframeProxy.prototype.getOpenerIframe",_.ge.prototype.ya);(0,_.M)("IframeProxy.prototype.getOpenParams",_.ge.prototype.ba);(0,_.M)("IframeProxy.prototype.getParams",_.ge.prototype.Oa);(0,_.M)("IframeProxy.prototype.removeCallback",_.ge.prototype.Bb);(0,_.M)("IframeWindow",_.he);
(0,_.M)("IframeWindow.prototype.close",_.he.prototype.close);(0,_.M)("IframeWindow.prototype.onClosed",_.he.prototype.b);(0,_.M)("iframes.util.getTopMostAccessibleWindow",_.R.D.jc);(0,_.M)("iframes.handlers.get",_.R.Rb.get);(0,_.M)("iframes.handlers.set",_.R.Rb.set);(0,_.M)("iframes.resizeMe",_.R.fk);(0,_.M)("iframes.setVersionOverride",_.R.Ak);


}catch(e){_._DumpException(e)}
try{
_.ne=function(a,c,f){return a[c]=a[c]||f};_.oe=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};_.pe=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.qe=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.ca(),h=g.parentNode,k=f.width,f=f.height;(0,_.oe)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";k&&(g.width=k+"px");f&&(g.height=f+"px");(k=c?c.title:_.r)&&a.ca().setAttribute("title",k)};
_.re=window;(0,_.ne)(_.re,"gapi",{});_.se={open:function(a){var c=window.document.getElementById(a.ba().container);return a.La(c,{style:(0,_.pe)(c,a)})},attach:function(a,c){var f=window.document.getElementById(a.ba().container);a.dm(c);a.cm({style:(0,_.pe)(f,a)})}};_.se.onready=_.qe;_.se.onRenderStart=_.qe;_.se.close=function(a){var c=a.Q();c&&c.removeChild(a.ca())};_.R.ka("inline",_.se);


}catch(e){_._DumpException(e)}
try{
_.te=function(a,c){this.b=a;this.bc=c};_.ue=function(a){this.w=this.Jb=a;this.n=_.r;this.slf=0;this.ssh=_.t;this.sen=_.q;this.shl=this.itm=_.r};_.te.prototype.nf=function(a){this.b.or(this.bc,a)};_.te.prototype.F=function(){this.b.oc(this.bc)};_.ue.prototype.sm=function(a,c){this.Jb.pk(new _.te(a,this));this.n=c};_.ue.prototype.sh=function(){this.Jb.show()};_.ue.prototype.hi=function(){this.Jb.jj()};_.ue.prototype.cl=function(){this.Jb.close()};_.ue.prototype.en=function(){this.Jb.enable()};_.ue.prototype.di=function(){this.Jb.disable()};_.ue.prototype.hl=function(a){this.Jb.Mm(a)};_.ue.prototype.vr=function(a,c){this.Jb.Li(a,c)};


}catch(e){_._DumpException(e)}
try{


}catch(e){_._DumpException(e)}
try{
_.ve=function(a){this.bc=a;this.Ka=0;this.ze=_.t;this.Ai=_.q;this.Ce=_.r};_.we=function(a){return 5==a.Ka||4==a.Ka};
_.xe=function(a,c,f){this.d=a||{};this.i=c||0;this.j=f||0;a={};c=(0,_.D)(this.vg,this);a.fc=c;c=(0,_.D)(this.xf,this);a.rc=c;c=(0,_.D)(this.Gf,this);a.sc=c;c=(0,_.D)(this.ke,this);a.hc=c;c=(0,_.D)(this.Vd,this);a.cc=c;c=(0,_.D)(this.fj,this);a.os=c;c=(0,_.D)(this.ej,this);a.or=c;c=(0,_.D)(this.cj,this);a.oh=c;c=(0,_.D)(this.aj,this);a.oc=c;c=(0,_.D)(this.bj,this);a.oe=c;c=(0,_.D)(this.dj,this);a.oi=c;this.b=a};
_.ye=function(a,c){var f=a.j-a.i;0<f&&(f=(0,window.setTimeout)((0,_.D)(function(){(0,_.we)(c)||(c.Ka=4,this.Vd(c.dc()))},a),f),c.Ce=f)};_.ze=function(a,c){c.Ce!=_.r&&((0,window.clearTimeout)(c.Ce),c.Ce=_.r)};_.Ae=function(a,c){(0,_.ze)(a,c);c.Ka=5;var f=a.d,g;for(g in f)f[g]==c&&delete f[g]};_.Be=function(a,c){return a.d[c.n]};_.Ce=function(a){this.b=a};_.De=function(){_.xe.call(this)};
_.Ee=function(a){if(window.___jsl.man)a(window.___jsl.man);else if(window.gbar){var c=function(){var c=new _.Ce(window.gbar.wg);window.___jsl.man=c;a(c)};window.gbar.wg?c():window.gbar.qm(c)}else c=new _.De,window.___jsl.man=c,a(c)};_.Fe=function(){return window.___jsl.man};_.ve.prototype.dc=(0,_.x)("bc");_.ve.prototype.isEnabled=(0,_.x)("Ai");_.ve.prototype.ja=(0,_.ba)("Ai");
_.C=_.xe.prototype;_.C.xf=function(a,c,f){try{a=a+(c!=_.r?"_"+c:""),f.sm(this.b,a),this.d[a]=new _.ve(f)}catch(g){return _.t}return _.q};_.C.vg=function(a,c){var f=this.d[a+(c!=_.r?"_"+c:"")];return f?f.dc():_.r};_.C.Gf=function(a){var c=(0,_.Be)(this,a);if(c&&(2==c.Ka||3==c.Ka)&&c.isEnabled()&&!c.ze){try{a.sh()}catch(f){}c.ze=_.q}};_.C.ke=function(a){var c=(0,_.Be)(this,a);if(c&&(2==c.Ka||3==c.Ka||(0,_.we)(c))&&c.ze){try{a.hi()}catch(f){}c.ze=_.t}};
_.C.Vd=function(a){var c=(0,_.Be)(this,a);if(c&&5!=c.Ka){try{this.ke(a),a.cl()}catch(f){}(0,_.Ae)(this,c)}};_.C.fj=function(a){var c=(0,_.Be)(this,a);c&&0==c.Ka&&(this.i?(a=(0,window.setTimeout)((0,_.D)(function(){(0,_.we)(c)||(0,_.ye)(this,c)},this),this.i),c.Ce=a):(0,_.ye)(this,c),c.Ka=1)};_.C.ej=function(a){if((a=(0,_.Be)(this,a))&&!(0,_.we)(a)&&1==a.Ka)(0,_.ze)(this,a),a.Ka=3};_.C.cj=function(a){if((a=(0,_.Be)(this,a))&&!(0,_.we)(a))a.ze=_.t};
_.C.aj=function(a){var c=(0,_.Be)(this,a);if(c&&!(0,_.we)(c)){try{this.ke(a)}catch(f){}(0,_.Ae)(this,c)}};_.C.bj=function(a){if((a=(0,_.Be)(this,a))&&!(0,_.we)(a))a.Ka=4,this.Vd(a.dc())};_.C.dj=function(a,c){var f=(0,_.Be)(this,a);f&&!(0,_.we)(f)&&(2<=c&&4>=c&&!(0,_.we)(f))&&((0,_.ze)(this,f),f.Ka=2)};
_.C=_.Ce.prototype;_.C.xf=function(a,c,f){return this.b.rc(a,c,f)};_.C.vg=function(a,c){return this.b.fc(a,c)};_.C.Gf=function(a){this.b.sc(a)};_.C.ke=function(a){this.b.hc(a)};_.C.Vd=function(a){this.b.cc(a)};_.C.fj=function(a){this.b.os(a)};_.C.ej=function(a,c){this.b.or(a,c)};_.C.cj=function(a){this.b.oh(a)};_.C.aj=function(a){this.b.oc(a)};_.C.bj=function(a,c,f,g,h,k){this.b.oe(a,c,f,g,h,k)};_.C.dj=function(a,c,f,g){this.b.oi(a,c,f,g)};
(0,_.E)(_.De,_.xe);

}catch(e){_._DumpException(e)}
try{
_.Ge=function(a){if("complete"===_.Ma.readyState)a();else{var c=_.t,f=function(){if(!c)return c=_.q,a.apply(this,arguments)};_.La.addEventListener?(_.La.addEventListener("load",f,_.t),_.La.addEventListener("DOMContentLoaded",f,_.t)):_.La.attachEvent&&(_.La.attachEvent("onreadystatechange",function(){"complete"===_.Ma.readyState&&f.apply(this,arguments)}),_.La.attachEvent("onload",f))}};_.He=function(){var a;if((a=window.Object.create)&&_.Ie.test(a))a=a(_.r);else{a={};for(var c in a)a[c]=_.n}return a};
_.Je=function(a){var c=(0,_.L)(a);return"undefined"!==typeof c?c:(0,_.L)("gwidget/"+a)};_.Ke=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.Le=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.r};_.Me=function(a){return a.dp&&window.gbar&&window.gapi.load};
_.Ne=function(a,c){var f=new _.Oe;f.t.start=c.t.start;f.t.blt=c.t.blt;var g=c.t.rpcqi;g&&(f.t.rpcqi=g);f.name=a.$c;f.tick("_widget");(0,_.ne)(_.Pe,"csi",[]).push(f);return f};_.Qe=function(a,c,f,g){return _.R.open(a,c,f,g)};_.Re=function(a,c){for(var c=c||[],f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};_.Se=function(a,c){for(var f in _.Te)if(_.Te.hasOwnProperty(f)){var g=_.Te[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};
_.Ue=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.Ve)(c[g],c,_.We));return f};_.Xe=function(a,c,f,g){var h=(0,_.Ue)(a.ga,f);a.dk.push({element:c,ga:h,Fd:(0,_.Se)(h,(0,_.Ue)(a.Wj,f)),Id:g,pm:!!f["data-onload"]})};_.Ye=function(a){function c(){for(var c=a.dk,g=a.xh;0<c.length;)g(c.shift())}(0,_.Me)(a)?(0,_.Ee)(c):c()};_.Ve=function(a){return a};_.Ze=function(){};_.$e=function(a){this.d=a;this.b=_.r};_.Ie=/\[native code\]/;_.af={};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.pi={};window.__gapi_jstiming__.Do=1;_.bf=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.n?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.bf;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.cf=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var k=window.chrome;if(k&&(k=k.loadTimes)){k().wasFetchedViaSpdy&&(g+="&p=s");if(k().wasNpnNegotiated){var g=g+"&npn=1",m=k().npnNegotiatedProtocol;m&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(m))}k().wasAlternateProtocolAvailable&&(g+="&apa=1")}var p=a.t,s=p.start,k=[],m=[],u;for(u in p)if("start"!=u&&0!=u.indexOf("_")){var w=p[u][1];w?p[w]&&
m.push(u+"."+(0,_.bf)(a,u,p[w][0])):s&&k.push(u+"."+(0,_.bf)(a,u))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,m.length?"&it="+m.join(","):"","",g,"&rt=",k.join(",")].join("");if(!a)return"";var g=new window.Image,B=window.__gapi_jstiming__.Do++;window.__gapi_jstiming__.pi[B]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.pi[B]};g.src=a;g=_.r;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.t,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var k;"prerender"==window.document.webkitVisibilityState?k=_.t:((0,_.cf)(a,c,f),k=_.q);k&&(g=_.q,window.document.removeEventListener("webkitvisibilitychange",h,_.t))}};window.document.addEventListener("webkitvisibilitychange",h,_.t);return""}return(0,_.cf)(a,c,f)}};
_.Pe=(0,_.ne)(_.re,"___jsl",(0,_.He)());(0,_.ne)(_.Pe,"I",0);(0,_.ne)(_.Pe,"hel",10);_.gf=["div"];_.hf="onload";_.jf=_.q;_.kf=window.__gapi_jstiming__;_.Oe=_.kf&&_.kf.Timer;_.lf=_.kf&&_.kf.load;_.mf=_.kf&&_.kf.report;_.nf=_.Oe&&_.lf&&_.mf;_.We=_.r;_.We=(0,_.L)();(0,_.L)("gwidget");_.of=(0,_.Je)("parsetags");_.hf="explicit"===_.of||"onload"===_.of?_.of:_.hf;_.pf=(0,_.Je)("google_analytics");"undefined"!==typeof _.pf&&(_.jf=!!_.pf);_.qf={};_.qf.width=[(0,_.Ke)(450)];_.qf.height=[(0,_.Ke)(24)];_.qf.callback=[_.Le];_.qf.onready=[_.Le];
_.qf.lang=[function(){return(0,_.Je)("lang")||"en-US"},"hl"];_.qf.iloader=[function(){return _.Pe.ILI},"iloader"];_.Te=_.qf;
_.df={zb:function(a){function c(){"onload"===_.hf&&p.go()}function f(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[h.Mk]=1;h.nh=c}var g,h={};h.$c=a[0];h.Th=-1;h.Sh="___"+h.$c+"_";h.Mk="g:"+h.$c;h.Mn="g-"+h.$c;h.dk=[];h.ga={};h.Zf=[];h.ng=[];a[1]&&(h.Wj=a[1]);h.ga=a[2]||{};for(var k in _.Te)_.Te.hasOwnProperty(k)&&!h.ga.hasOwnProperty(k)&&(h.ga[k]=_.Te[k]);a[3]&&(h.Zf=a[3]);a[4]&&f(a[4]);a[5]&&(h.Hd=a[5]);h.dp=a[7]===_.q;h.wo=a[8];h.nh||f(_.gf);if(a=a[6])if("number"==typeof a.length){h.ng=
a;for(var m=a.length-1;0<=m;--m)h.ga[a[m]]=[_.Le]}else for(m in a)a.hasOwnProperty(m)&&!h.ga.hasOwnProperty(m)&&(h.ng.push(m),h.ga[m]=a[m]);h.xh=function(a){function c(){var a="",f="m"+(window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/)?"1":"0"),g="n"+Uo;try{var h=(0,_.Re)("e",(0,_.L)("lexps"));h.push(g);h.push(f);0==Uo&&h.push(f+g);h.push(_.hf);h.push("l"+((0,_.L)("isPlusUser")?"1":"0"));f=h;if(window.performance){var k=window.performance.timing;if(k){var m=k.navigationStart,
p=k.domContentLoadedEventStart;if(m&&p){k=(p-m)/1E3;1>k&&(k=1);var s=window.Math.floor(window.Math.log(k)/window.Math.log(2));6>=s&&f.push("p_gt"+window.Math.pow(2,s)+"s")}}}h=(0,_.Re)("abc_",h);a=h.join(",")}catch(u){}(0,_.mf)(Zb,{e:a});Vo++;Zb=(0,_.Ne)(Ej,_.lf)}function f(a,c){qb.Y("ready",a);_.Q.N("widget-interactive-"+qb.id,a);_.Q.N("widget-csi-tick-"+qb.id,c)}function g(a){var a=a||qb,c=qb.Ue(a.width);c&&Pg.style.width!=c.Ec&&(Pg.style.width=c.Ec);if((a=qb.Ue(a.height))&&Pg.style.height!=a.Ec)Pg.style.height=
a.Ec}h.Th++;var k=[];h.Hd&&(k[0]=a.element,k[1]=a.Id,h.Hd("s",k),a.Id=k[1]);var m=a.element,p=m.parentNode,s=a.ga;if(0===a.Id){var P=window.document.createElement("div");p.insertBefore(P,m);p.removeChild(m);m=P}P=m.style;if(m.id){if(3===a.Id&&0===m.id.indexOf(h.Sh)){var T=m.nextSibling;T&&T.getAttribute("data-gapistub")&&p.removeChild(T);P.cssText=""}}else{var p=m,T=h.Sh,U=h.$c,na=(0,_.ne)(_.Pe,"WI",(0,_.He)());window.Object.prototype.hasOwnProperty.call(na,U)||(na[U]=0);var Qg=na[U];na[U]=Qg+1;p.id=
T+Qg}s.height&&(P.height=s.height+"px");s.width&&(P.width=s.width+"px");P.display||(P.display="inline-block");(0,_.Me)(h)&&(P.display="none");(0,_.oe)(m);var vd=":"+h.$c;":plus"==vd&&(a.Fd&&a.Fd.action)&&(vd+="_"+a.Fd.action);var P={},p=h.Zf[0],T=s.callback,rb=h.Zf[1];if(rb&&_.jf)var Tv=T||(0,_.v)(),T=function(a){var c=rb(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.r):window._gaq&&window._gaq.push(["_trackSocial",
"Google",c,a.href||_.r])}catch(g){}Tv(a)};p&&T&&(P[p]=T);p=h.ng;for(T=p.length-1;0<=T;--T){var db=p[T];(U=s[db])&&(P[db]=U)}p={};for(db in a.Fd)a.Fd[db]!=_.r&&(p[db]=a.Fd[db]);db={container:m.id,style:"inline",height:s.height,width:s.width};if(3===a.Id){if(!_.R.aa("attach")){var wd={},ef=_.R.aa("inline"),uc;for(uc in ef)ef.hasOwnProperty(uc)&&(wd[uc]=ef[uc]);wd.open=function(a){var c;a:{c=window.document.getElementById(a.ba().container).getElementsByTagName("IFRAME");for(var f=0;f<c.length;++f){var g=
c[f];if(g.id&&/^I\d+_\d+$/.test(g.id)){c=g;break a}}c=_.n}return c?ef.attach(a,c):ef.open(a)};_.R.ka("attach",wd)}db.style="attach"}else if((0,_.Me)(h)){db._ct=h.$c;db._ci=h.Th;if(!_.R.aa("inline-managed")){uc={};var ff=_.R.aa("inline");for(wd in ff)ff.hasOwnProperty(wd)&&(uc[wd]=ff[wd]);uc.open=function(a){ff.open(a);var c=new _.ue(new _.$e(a));(0,_.Fe)().xf(a.ba()._ct,a.ba()._ci,c)&&(a=c[_.af.bl.jl],a.b&&(a=a.b,a.b.os(a.bc)))};uc.onready=function(a){ff.onready(a);var c=(0,_.Fe)();if(a=c.vg(a.ba()._ct,
a.ba()._ci)){var f=a[_.af.bl.jl];f.b&&f.b.nf({});c.Gf(a)}};_.R.ka("inline-managed",uc)}db.style="inline-managed"}h.Hd&&(k[2]=db,k[3]=p,k[4]=P,h.Hd("i",k),a.Id=k[1]);var qb=function(a){var c=_.Qe.apply(_.r,[vd].concat([].slice.call(arguments,0)));if(s.onready){var f=_.t,g=function(){f||(f=_.q,s.onready.call(_.r))};c.Y("ready",g);c.Y("renderstart",g)}(0,_.Ze)(c);return c}(db,p,P),Pg=m;qb.Y("ready",g);qb.Y("renderstart",g);qb.Y("resize",g);var Ej=h,Wo=a.pm;if(_.nf){var Uo=Ej.Th,Zb=(0,_.Ne)(Ej,_.lf),
Xo=_.t,Yo=function(){if(!Xo){Xo=_.q;var a=qb.ca()["data-csi-wdt"]||_.n;Zb.tick("wdi","_widget",a);Wo&&Zb.tick("wdt",_.n,a)}};qb.Y("renderstart",Yo);var Zo=_.t,Vo=0;f(function(){Zo||(Zo=_.q,Yo(),Zb.tick("wri","_widget"),Wo&&Zb.tick("wrt"),(0,_.Ge)(c))},function(a,f,g,h){if(h!=_.r)f=(new window.Date).getTime(),Zb.tick("_"+a,_.n,f),Zb.tick(a,"_"+a,f+h);else{if(f&&!Zb.t[f])return;Zb.tick(a,f||_.n,g||_.n)}0<Vo&&c()})}else a=(0,_.v)(),f(a,a);k[5]=qb;h.Hd&&h.Hd("e",k)};g=h;if(m=g.wo)for(a=0;a<m.length;a++)(new window.Image).src=
m[a];var p={O:function(a,c,f){a=("string"===typeof a?window.document.getElementById(a):a)||_.n;c=c||{};c.callback=f||c.callback;a&&1===a.nodeType&&(0,_.Xe)(g,a,c,1);(0,_.Ye)(g)},go:function(a){if(a=("string"===typeof a?window.document.getElementById(a):a)||window.document.body){var c;c=[];for(var f=a.getElementsByTagName("iframe"),h={},k=0;k<f.length;++k){var m=f[k].parentNode,p=m.id;if("div"==m.tagName.toLowerCase()&&p&&p.indexOf&&0==p.indexOf(g.Sh)&&!h[p]){var s;s=m;var P=s.getAttribute("data-gwattr");
if(P!=_.r){s.removeAttribute("data-gwattr");s=P.split(":");for(var P={},T=0;T<s.length;++T){var U=s[T].split("="),na=window.decodeURIComponent(U[0]),U=window.decodeURIComponent(U[1]);P[na]=U}s=P}else s=_.n;s&&(c.push({element:m,Xf:s}),h[p]=1)}}for(f=0;f<c.length;++f)h=c[f],(0,_.Xe)(g,h.element,h.Xf,3);c=[];a=a.getElementsByTagName("*");f=(0,window.RegExp)("(?:^|\\s)"+g.Mn+"(?:$|\\s)");for(h=0;h<a.length;++h)if(k=a[h],m=k.nodeName.toLowerCase(),!k.getAttribute("data-gapistub")&&(g.nh[m]||g.nh["*"])){p=
"";if(m!==g.Mk&&(p="data-",!f.test(k.className||k.getAttribute("class"))))continue;s=m={};P=g.Wj;T=k;na=p;U=_.n;for(U in P)P.hasOwnProperty(U)&&(s[U]=T.getAttribute(na+U));s=m;P=g.ga;T=k;na=_.n;for(na in P)P.hasOwnProperty(na)&&(s[na]=T.getAttribute(p+na));c.push({element:k,Xf:m})}for(f=0;f<c.length;++f)h=c[f],(0,_.Xe)(g,h.element,h.Xf,0);(0,_.Ye)(g)}},b:function(){_.Pe.WI=(0,_.He)()}};try{c()}catch(s){}"complete"!==_.Ma.readyState&&(0,_.Ge)(c);return p}};
_.af=_.af||{};_.C=_.$e.prototype;_.C.pk=(0,_.ba)("b");_.C.Li=function(a,c){c({})};_.C.show=function(){this.d.Q().style.display="inline-block"};_.C.jj=function(){this.d.Q().style.display="none"};_.C.close=function(){this.d.close({})};_.C.enable=(0,_.v)();_.C.disable=(0,_.v)();


}catch(e){_._DumpException(e)}
try{
_.kq=(window.gapi||{}).load;

}catch(e){_._DumpException(e)}
try{
_.R.Df("bubble",function(a){(0,_.kq)("iframes-styles-bubble",a)});

}catch(e){_._DumpException(e)}
try{
_.yp=function(a,c,f){return"string"==typeof a&&c[a.toLowerCase()]?a.toLowerCase():f};_.zp=function(a){var c=window.document.createElement("div"),f=window.document.createElement("a");f.href=a;c.appendChild(f);c.innerHTML=c.innerHTML;return c.firstChild.href};_.Ap=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Bp=function(a,c,f,g){if(a)a=(0,_.zp)(a);else a:{a=(a=g)||"canonical";c=window.document.getElementsByTagName("link");f=0;for(g=c.length;f<g;f++){var h=c[f],k=h.getAttribute("rel");if(k&&k.toLowerCase()==a&&(h=h.getAttribute("href")))if(h=(0,_.zp)(h)){a=h;break a}}a=window.location.href}return a};_.Cp=function(a){a.source=[_.r,"source"];a.expandTo=[_.r,"expandTo"];a.align=[_.Dp];a.annotation=[_.Ep];a.origin=[_.Ap]};_.Fp=function(a,c){if("string"==typeof a){var f;for(f=0;f<c.length;f++)if(c[f]==a.toLowerCase())return a.toLowerCase()}};
_.Dp=function(a){return(0,_.Fp)(a,_.Gp)};_.Ep=function(a){return(0,_.Fp)(a,_.Hp)};_.Ip=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.Jp=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.Kp=function(a){if((0,_.Ip)(a))return"true"};_.Lp=function(a){return(0,_.yp)(a,_.Mp,"standard")};_.Np=function(a,c){return"tall"==(0,_.Lp)(c)?"true":a==_.r||(0,_.Ip)(a)?"true":"false"};
_.Gp=["left","right"];_.Hp="inline bubble none only pp vertical-bubble".split(" ");_.Mp={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.Op={href:[_.Bp,"url"],width:[_.Jp],size:[_.Lp],resize:[_.Kp],autosize:[_.Kp],count:[function(a,c){return(0,_.Np)(c.count,c.size)}],db:[function(a,c,f){a==_.r&&f&&(a=f.db,a==_.r&&(a=f.gwidget&&f.gwidget.db));return(0,_.Ip)(a)?1:_.n}],ecp:[function(a,c,f){a==_.r&&f&&(a=f.ecp,a==_.r&&(a=f.gwidget&&f.gwidget.ecp));if((0,_.Ip)(a))return"true"}],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.Kp],recommendations:[],fu:[],ad:[_.Kp],cr:[_.Jp],ag:[_.Jp],"fr-ai":[], "fr-sigh":[]};


}catch(e){_._DumpException(e)}
try{
_.Gw=function(a,c,f){a=(0,_.Ep)(a);c=(0,_.Lp)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.Mp[c]["false"].height};if("bubble"!=a){if("none"==a)return _.Mp[c]["false"];if("pp"==a)return _.Hw}}return _.Mp[c]["true"]};_.Hw={width:180,height:35};
_.Iw={"0":"plusone"};_.Jw=(0,_.L)("iframes/plusone/preloadUrl");_.Jw&&(_.Iw[8]=_.Jw);(0,_.Cp)(_.Op);_.Iw[1]=_.Op;_.Iw[2]={width:[function(a,c){return c.annotation?(0,_.Gw)(c.annotation,c.size,c).width:_.Mp[(0,_.Lp)(c.size)][(0,_.Np)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.Gw)(c.annotation,c.size,c).height:_.Mp[(0,_.Lp)(c.size)][(0,_.Np)(c.count,c.size)].height}]};_.Iw[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.r}];_.Iw[4]=["div","button"]; _.Iw[6]=["onstartinteraction","onendinteraction","onpopup"];_.Ja=_.Ka=_.df.zb(_.Iw);
(0,_.M)("gapi.plusone.render",_.Ka.O);(0,_.M)("gapi.plusone.go",_.Ka.go);(0,_.M)("googleapisv0.plusone.render",_.Ja.O);(0,_.M)("googleapisv0.plusone.go",_.Ja.go);

}catch(e){_._DumpException(e)}
});

// Copyright 2002-2012 Google Inc.
