var DISQUS=function(f){var h={AssertionError:function(d){this.message=d}};h.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};h.assert=function(d,f){if(!d)throw new h.AssertionError(f);};var k=[];h.define=function(d,j){typeof d==="function"&&(j=d,d="");for(var a=d.split("."),c=a.shift(),e=h,l=(j||function(){return{}}).call({overwrites:function(c){c.__overwrites__=!0;return c}},f);c;)e=e[c]?e[c]:e[c]={},c=a.shift();for(var i in l)l.hasOwnProperty(i)&&
(l.__overwrites__||e[i]!==null&&h.assert(!e.hasOwnProperty(i),"Unsafe attempt to redefine existing module with "+i),e[i]=l[i],k.push(function(c,a){return function(){delete c[a]}}(e,i)));return e};h.use=function(d){return h.define(d)};h.cleanup=function(){for(var d=0;d<k.length;d++)k[d]()};return h}(this);
DISQUS.define(function(f,h){var k=f.document,d=k.getElementsByTagName("head")[0]||k.body,j={running:!1,timer:null,queue:[]};DISQUS.defer=function(a,c){function e(){var c=j.queue;if(c.length===0)j.running=!1,clearInterval(j.timer);for(var a=0,e;e=c[a];a++)e[0]()&&(c.splice(a--,1),e[1]())}j.queue.push([a,c]);e();if(!j.running)j.running=!0,j.timer=setInterval(e,100)};DISQUS.each=function(a,c){var e=a.length,d=Array.prototype.forEach;if(isNaN(e))for(var i in a)a.hasOwnProperty(i)&&c(a[i],i,a);else if(d)d.call(a,
c);else for(d=0;d<e;d++)c(a[d],d,a)};DISQUS.extend=function(a){DISQUS.each(Array.prototype.slice.call(arguments,1),function(c){for(var e in c)a[e]=c[e]});return a};DISQUS.serializeArgs=function(a){var c=[];DISQUS.each(a,function(a,d){a!==h&&c.push(d+(a!==null?"="+encodeURIComponent(a):""))});return c.join("&")};DISQUS.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};DISQUS.serialize=function(a,c,e){c&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=DISQUS.serializeArgs(c));
if(e)return c={},c[(new Date).getTime()]=null,DISQUS.serialize(a,c);c=a.length;return a.charAt(c-1)=="&"?a.slice(0,c-1):a};DISQUS.require=function(a,c,e,f,i){function h(b){if(b.type=="load"||/^(complete|loaded)$/.test(b.target.readyState))f&&f(),o&&clearTimeout(o),DISQUS.bean.remove(b.target,j,h)}var g=k.createElement("script"),j=g.addEventListener?"load":"readystatechange",o=null;g.src=DISQUS.serialize(a,c,e);g.async=!0;g.charset="UTF-8";(f||i)&&DISQUS.bean.add(g,j,h);i&&(o=setTimeout(function(){i()},
2E4));d.appendChild(g);return DISQUS};DISQUS.requireStylesheet=function(a,c,e){var f=k.createElement("link");f.rel="stylesheet";f.type="text/css";f.href=DISQUS.serialize(a,c,e);d.appendChild(f);return DISQUS};DISQUS.requireSet=function(a,c,e){var d=a.length;DISQUS.each(a,function(a){DISQUS.require(a,{},c,function(){--d===0&&e()})})};DISQUS.injectCss=function(a){var c=k.createElement("style");c.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");f.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,
"https://"));c.styleSheet?c.styleSheet.cssText=a:c.appendChild(k.createTextNode(a));d.appendChild(c)}});
DISQUS.define("JSON",function(){function f(b){return b<10?"0"+b:b}function h(b){c.lastIndex=0;return c.test(b)?'"'+b.replace(c,function(b){var c=i[b];return typeof c==="string"?c:"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function k(b,c){var a,d,p,f,i=e,g,m=c[b];m&&typeof m==="object"&&typeof m.toJSON==="function"&&!j&&(m=m.toJSON(b));typeof n==="function"&&(m=n.call(c,b,m));switch(typeof m){case "string":return h(m);case "number":return isFinite(m)?String(m):"null";case "boolean":case "null":return String(m);
case "object":if(!m)return"null";e+=l;g=[];if(Object.prototype.toString.apply(m)==="[object Array]"){f=m.length;for(a=0;a<f;a+=1)g[a]=k(a,m)||"null";p=g.length===0?"[]":e?"[\n"+e+g.join(",\n"+e)+"\n"+i+"]":"["+g.join(",")+"]";e=i;return p}if(n&&typeof n==="object"){f=n.length;for(a=0;a<f;a+=1)d=n[a],typeof d==="string"&&(p=k(d,m))&&g.push(h(d)+(e?": ":":")+p)}else for(d in m)Object.hasOwnProperty.call(m,d)&&(p=k(d,m))&&g.push(h(d)+(e?": ":":")+p);p=g.length===0?"{}":e?"{\n"+e+g.join(",\n"+e)+"\n"+
i+"}":"{"+g.join(",")+"}";e=i;return p}}var d={},j=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var a=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
c=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,e,l,i={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},n;d.stringify=function(b,c,a){var d;l=e="";if(typeof a==="number")for(d=0;d<a;d+=1)l+=" ";else typeof a==="string"&&(l=a);if((n=c)&&typeof c!=="function"&&(typeof c!=="object"||typeof c.length!=="number"))throw Error("JSON.stringify");return k("",{"":b})};d.parse=function(b,c){function d(b,
a){var e,f,i=b[a];if(i&&typeof i==="object")for(e in i)Object.hasOwnProperty.call(i,e)&&(f=d(i,e),f!==void 0?i[e]=f:delete i[e]);return c.call(b,a,i)}var e,b=String(b);a.lastIndex=0;a.test(b)&&(b=b.replace(a,function(b){return"\\u"+("0000"+b.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(b.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+b+")"),
typeof c==="function"?d({"":e},""):e;throw new SyntaxError("JSON.parse");};var g={a:[1,2,3]},q,o;if(Object.toJSON&&Object.toJSON(g).replace(/\s/g,"")==='{"a":[1,2,3]}')q=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(g='{"a":[1,2,3]}'.evalJSON(),g.a&&g.a.length===3&&g.a[2]===3&&(o=function(b){return b.evalJSON()}));(function(){var b=[1,2,3];typeof b.toJSON==="function"&&(b=b.toJSON(),j=!(b&&b.length===3&&b[2]===3))})();if(j||!q||!o)return{stringify:d.stringify,parse:d.parse};return{stringify:q,
parse:o}});
DISQUS.define(function(){function f(a){for(c=1;a=h.shift();)a()}var h=[],k,d=document,j=d.documentElement,a=j.doScroll,c=/^loade|c/.test(d.readyState),e;d.addEventListener&&d.addEventListener("DOMContentLoaded",k=function(){d.removeEventListener("DOMContentLoaded",k,!1);f()},!1);a&&d.attachEvent("onreadystatechange",k=function(){/^c/.test(d.readyState)&&(d.detachEvent("onreadystatechange",k),f())});e=a?function(a){self!=top?c?a():h.push(a):function(){try{j.doScroll("left")}catch(c){return setTimeout(function(){e(a)},50)}a()}()}:
function(a){c?a():h.push(a)};return{domready:e}});
DISQUS.define("Events",function(){var f=/\s+/,h={on:function(h,d,j){var a,c;if(!d)return this;h=h.split(f);for(a=this._callbacks||(this._callbacks={});c=h.shift();)c=a[c]||(a[c]=[]),c.push(d),c.push(j);return this},off:function(h,d,j){var a,c,e;if(!(c=this._callbacks))return this;if(!h&&!d&&!j)return delete this._callbacks,this;for(h=h?h.split(f):_.keys(c);a=h.shift();)if(!(e=c[a])||!d&&!j)delete c[a];else for(a=e.length-2;a>=0;a-=2)d&&e[a]!==d||j&&e[a+1]!==j||e.splice(a,2);return this},trigger:function(h){var d,
j,a,c,e,l,i;if(!(j=this._callbacks))return this;i=[];h=h.split(f);c=1;for(e=arguments.length;c<e;c++)i[c-1]=arguments[c];for(;d=h.shift();){if(l=j.all)l=l.slice();if(a=j[d])a=a.slice();if(a){c=0;for(e=a.length;c<e;c+=2)a[c].apply(a[c+1]||this,i)}if(l){d=[d].concat(i);c=0;for(e=l.length;c<e;c+=2)l[c].apply(l[c+1]||this,d)}}return this}};h.bind=h.on;h.unbind=h.off;return h});
DISQUS.define(function(f,h){function k(){throw Error(Array.prototype.join.call(arguments," "));}function d(b,a,c){if(b.addEventListener)b.addEventListener(a,c,!1);else if(b.attachEvent)b.attachEvent("on"+a,c);else throw Error("No event support.");}var j=f.document,a=DISQUS.use("JSON");if(!(DISQUS!==h&&DISQUS.version&&DISQUS.version()=="__version__")){var c={},e={},l=0;d(f,"message",function(b){var c,d;for(d in e)if(Object.prototype.hasOwnProperty.call(e,d)&&b.origin==e[d].origin){c=!0;break}if(c)switch(c=
a.parse(b.data),(d=e[c.sender])||k("Message from our server but with invalid sender UID:",c.sender),c.scope){case "host":d.trigger(c.name,c.data);break;case "global":DISQUS.trigger(c.name,c.data);break;default:k("Message",c.scope,"not supported. Sender:",b.origin)}},!1);d(f,"hashchange",function(){DISQUS.trigger("window.hashchange",{hash:f.location.hash})},!1);d(f,"resize",function(){DISQUS.trigger("window.resize")},!1);var i=function(){DISQUS.trigger("window.scroll")};(function(b,c,a,e){var p=(new Date).getTime();
d(b,c,function(){var b=(new Date).getTime();b-p>=e&&(p=b,a())})})(f,"scroll",i,250);(function(b,c,a,e){var p;d(b,c,function(b){p&&clearTimeout(p);p=setTimeout(function(){a(b)},e)})})(f,"scroll",i,300);j.getElementsByTagName("html");d(j,"click",function(){DISQUS.trigger("window.click")});i=function(){this.uid=l++;c[this.uid]=this};DISQUS.extend(i.prototype,DISQUS.Events);i.prototype.destroy=function(){delete c[this.uid]};DISQUS.extend(i,{listByKey:function(){var b={},a;for(a in c)Object.prototype.hasOwnProperty.call(c,
a)&&(b[a]=c[a]);return b},list:function(){var b=[],a;for(a in c)Object.prototype.hasOwnProperty.call(c,a)&&b.push(c[a]);return b},get:function(b){if(Object.prototype.hasOwnProperty.call(c,b))return c[b];return null}});var n=function(b){b=b||{};this.isReady=!1;this.uid=b.uid||l++;this.elem=null;this.styles={};this.role=b.role||"application"};n.prototype.load=function(){var b=this.elem=j.createElement("iframe");b.setAttribute("id","dsq"+this.uid);b.setAttribute("data-disqus-uid",this.uid);b.setAttribute("allowTransparency",
"true");b.setAttribute("frameBorder","0");b.setAttribute("role",this.role);for(var a in this.styles)this.styles.hasOwnProperty(a)&&(b.style[a]=this.styles[a])};n.prototype.destroy=function(){this.elem&&this.elem.parentNode.removeChild(this.elem)};var g=function(b){var a=this;n.call(a,b);a.listeners={};a.origin=b.origin;a.target=b.target;a.container=b.container;a.styles={width:"100%",border:"none",overflow:"hidden",display:"none"};e[a.uid]=a;a.on("ready",function(){a.isReady=!0})};DISQUS.extend(g.prototype,
DISQUS.Events);g.prototype.load=function(b){n.prototype.load.call(this);var a=this.elem;a.setAttribute("width","100%");a.setAttribute("src",this.target+"#"+this.uid);d(a,"load",function(){a.style.display="";b&&b()});(j.getElementById(this.container)||j.body).appendChild(a);this.elem=a};g.prototype.sendMessage=function(b,c){var d=function(b,a,c){return function(){c.elem.contentWindow.postMessage(b,a)}}(a.stringify({scope:"client",data:{eventName:b,data:c}}),this.origin,this);if(this.isReady)d();else this.on("ready",
d)};g.prototype.getPosition=function(){for(var b=this.elem,a=0,c=0;b;)a+=b.offsetLeft,c+=b.offsetTop,b=b.offsetParent;return{top:c,left:a}};g.prototype.inViewport=function(b){var b=b||this.getPosition(),b=b.top,a=b+this.elem.offsetHeight,c=f.pageYOffset;return!(b>c+f.innerHeight||a<c)};g.prototype.destroy=function(){this.off();n.prototype.destroy.call(this)};var q=function(b){n.call(this,b);this.contents=b.contents;this.container=b.container;this.styles={width:"100%",border:"none",overflow:"hidden"};
b.styles=b.styles||{};for(var a in b.styles)b.styles.hasOwnProperty(a)&&(this.styles[a]=b.styles[a])};q.prototype.load=function(){n.prototype.load.call(this);var b=this.elem;b.setAttribute("scrolling","no");(j.getElementById(this.container)||j.body).appendChild(b);this.element=b;this.window=b.contentWindow;try{this.window.document.open()}catch(a){b.src="javascript:var d=document.open();d.domain='"+j.domain+"';void(0);"}this.document=this.window.document;this.document.write(this.contents);this.document.close();
if(b=this.document.body)this.element.style.height=b.offsetHeight+"px"};q.prototype.exec=function(b){b.call(this,this.window,this.document)};q.prototype.hide=function(){var b=this.element.style.display;if(b!=="none")this._display=b;this.element.style.display="none"};q.prototype.show=function(){this.element.style.display=this._display||"block"};q.prototype.click=function(b){d(this.document.body,"click",function(a){b(a)})};q.prototype.destroy=n.prototype.destroy;var o=DISQUS.extend({},DISQUS.Events);
return{IFRAME:"__widget_iframe__",log:function(b){var a=j.getElementById("messages");if(a){var c=j.createElement("p");c.innerHTML=b;a.appendChild(c)}},version:function(){return"__version__"},on:o.on,off:o.off,trigger:o.trigger,Channel:g,Sandbox:q,App:i}}});
DISQUS.define(function(){function f(f){DISQUS.App.call(this);this.switches={};this.frame=new DISQUS.Channel({target:"http://mediacdn.disqus.com/1344364156/build/next-switches/client.html",container:f.container,origin:"http://mediacdn.disqus.com"});var k=this;this.frame.load(function(){k.frame.elem.style.display="none"})}f.prototype=DISQUS.extend({fetch:function(f){var k=this,f=f||{},d=f.success;delete f.success;this.frame.on("switches.received",function(f){k.switches=f;DISQUS.trigger("switches.changed",
f);d&&d(f)});this.frame.sendMessage("fetch",f)},enabled:function(f){return this.switches[f]?this.switches[f]:!1}},DISQUS.App.prototype);return{Switches:function(h){return new f(h)}}});
DISQUS.define(function(f,h){function k(a,c,d,e,f,b){return'<img width="'+a+'" height="'+c+'" alt="'+e+'" src="data:image/'+d+";base64,"+f+'"'+(b?'style="'+b+'"':"")+"/>"}function d(a){for(var c=DISQUS.App.list(),d=0,f=c.length,c=c[d];d<f;d++)c instanceof e&&a(c)}var j=f.document,a=["iVBORw0KGgoAAAANSUhEUgAAAEcAAAARCAYAAAH4YIFjAAAAGXRFWHRTb2Z0d2FyZQBB","ZG9iZSBJbWFnZVJlYWR5ccllPAAABwdJREFUeNpi/P//PwMhwAIiGBkZGeK6V8JVh9rq","dfrc0ixnEDb+wPD2rAAjMSYBBBBRisDWwKxCthIE/q8Q+A8yhCiTAAIIrCi+ZxVMZSAQ","r19UGs4IMxWd/X8Rw3/GOKDhW43fgzwF1hX7n5EJ2dSp2QFNUKcZwJ31/78CkvPBGkGG",
"MXidSUTWCxBAxAUAEQAcJzCvIXsDBPwsNBU2nbj+AMpdsFA8PAHsLZj3QC5D9hrIAEtN","+RMwAzRkxcB0iK3eQ6iQIRAnoMTE//8CyHwmWHQdv/7QAiZ44/ErMP383acsqNB5iMnP","lsFdsUZ6IU3CCCCA4AYBw8kBJgj06gGkmHJAFgPyQV4ExeQEoNgHJHUBQMoAWRzoerBe","YHgeQOJ/APIvQPkNUP4EuIdADBAGBRMQOABxQcakdSipHZldNGvL2zWHL8kD1d0HieVN","33QYqnc/EAfULNwJVw8KTniQwvjAdPz/SEwKmL1KfC5QjwEQr4e5AyVdA3P4ASCe8O3n","b1whmtib6r3IXlfpATBEFbpWH9ygJSdmBtXrOHPbyZWPXn1AqOZRwDSBS+YHo82SOQwi","ZnYMoS+EGC42nGdYzBiAnKpgGAbeA3ECkjwYQNnzH758///6o5cgofVIagy+/vgFF//y","/ecHJLn1/18AA+/teZBcPZL4eSTxBJg7AAKIaomRmpkeV2IG5UcDpMSsAM2zF4BiG9DU",
"FaCLQxPwBWCC/QBkg/QqoCVuEN4ASuDIaWc/DIMSItBxH0GCrkaqCVBxWO4BJWBQcK/P","mrL+I1S8H0i9h4mjFfX7GTRyIdEuHzIfZtb/Zdw3oGyQnvP/d9pNgRc+MLCwJMxxWk7A","I6Ar+YCWVSLLyYkJzIYlZqC6RGBhbg/lFwDlQHoDgfgALLfhjY8/X9XhpWPs/wWM7ody","MBwDylU8nOzyILYIH3cZslxBgM0cKHM+MOTAGCZnri7XCdS7ASgGLsc/fPlug9cxlrO/","wUvYxYwJwCgLwHAMcrVlqCJ9BVlchJ+7EhRyQPwAyGaAFnhgsOPMzUhQroLVAU76yp/g","Gp/vtQbTr45pwMWOp1oDQ6QQiGEi6+EJGLmah0YJQ6CVtu3ivecKYHIpE9b8BPqcDSna","wHSSu8m3eTvPyAHlzsPkDl25/wXMYAOq+XgtBFwIfn/GwCAOSq8HYCGCsNh8+hvksgYZ","IJchDkjljAKoHAKVJ6ByBbnmA5XESOL1oFIZSc9/cJkC1IukPuH/z/cw8fswdwyqcgYg",
"wAaVYwYbQEnDSI1LbGABEDcCC1lYS4yhfO42n+fvPm9GKsAZkfJDA7RcwwYmQM1CbpUU","ADU3AB3AjxJ7wFwAFGsAqp2A0mBDahww8Gv4Mvrf2AKXWyMzgeHbk3wwh5X/DGPkR1Oo","HlCmn49cGCABkL8SgZn8ANbAQQaV4ZBK6yGwgbDr3G2GNx+/gkqShMTe1V///vsnA/KY","joKECjBwMPQCW0EngOrNQWxbHQWGFA8zBlAj5eztpwwbjl9lyPG1DFOUEAIFDqxJB6ks","oC1ZN2NVsDm7zt4GNUhBgdUPrXwckWtQOJB0VQE2XRF8UQt9hodrIGw+FaDcWVjAwAsh","hsD7kAbPO2Dr78ZEBoZfHxQYHNYbwEogvIGjKSfOiNysBpaEL/acv8MODBhuUX7u00Bh","VVx6DZWlxHcDAxQEDl95AMZQAGqHLlSSFIanAnZWll0/f/8Bs2OcDB+5GavJVyGZtevs","rYdL9p2XQ6rZGcnKI54nZRj2uoMCAVr4K8JkQAKgJsdEYN12AbmYYSGqYGJk/NC8bO91",
"WHKUFRXgwace6ElDIF4PjHWHc3eeMZy98xSU8mB1mwE0FSQCU8ECZiZGVpi+yw9eLIfV","lUyMjIf+/f/Pu/bIlTtIdSX5hauo+RagxxMZfr2fwHB3IT/Dy4MMDI/BzTABaP2aAGzm","gPpN4gQDB1pmgIA+EAfcfvoGXl/mB1hXFuBxCLDs6oc26kBJZiIoxShLCqs9e/tp+vdf","v8ENB08Tdf9FwHKsMtxxTfvK/SGgbHfx3vNyoL2g7DjR30r74vqjV2yA6lXgbnI2WtoH","4yhEfGF4sAISSTcm9wOzDcidoE6lPTBLwRuyDMoJ5+DZagnLJIb/f3mh5edGcKoRs+5n","eHUUUgZxiIrhrK2wFchc7KwMmsByANjiAZUfoGzhCEpJIDlQowOYffqRC2RQS+f1x68H","Nx6/ygcqY9A7RMZAc5LcTS/zcLLZwcwB1evAzs/8pfsvwDu9yOplgRECzF4M8a7Gryw0","5NRB+sDtiC/3HjKcKeaDpgAEADVmNIDlsX4DqFPmCOvvMNxdkAAuX95dQFUPKnv06kEB",
"mQgNOLpV5QbQpAsrcz4QUC+AVJsgqxcgoNcBqQy5QIIdONUDALcn6c0dtMJ9AAAAAElF","TkSuQmCC"],c=["R0lGODlhEAALAPQAAP///z2LqeLt8dvp7u7090GNqz2LqV+fuJ/F1IW2ycrf51aatHWs","waXJ14i4ys3h6FmctUCMqniuw+vz9eHs8fb5+meku+Tu8vT4+cfd5bbT3tbm7PH2+AAA","AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQu","aW5mbwAh+QQJCwAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27if","DgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeR","vsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjoth",
"LOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh","+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+","YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY","5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAs","AAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00k","j5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpy","HCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAA","BS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7",
"AAAAAAAAAAAA"],e=function(a){DISQUS.App.call(this);this.settings=a;this.indicators={north:null,south:null};this._boundGlobalEvents=[];this.frame=null};DISQUS.extend(e.prototype,DISQUS.App.prototype);e.prototype.init=function(){function d(a,b){e._boundGlobalEvents.push(a);DISQUS.on(a,b,e)}var e=this,g=e.settings,l={f:g.forum,t_i:g.identifier,t_u:g.url||f.location.href,t_s:g.slug,t_t:g.title,s_o:g.sortOrder,c:g.useConman},o=DISQUS.isString(g.container)?j.getElementById(g.container):g.container,b=e.frame=
new DISQUS.Channel({origin:"http://disqus.com",target:DISQUS.serialize("http://disqus.com/next/lounge/client.html",l),container:g.container,uid:this.uid}),r=!1;if(f.postMessage){var s=j.createElement("div");s.innerHTML=k(71,17,"png","DISQUS",a.join(""))+k(16,11,"gif","...",c.join(""),"margin:0 0 3px 5px");o.appendChild(s)}l=function(){var a=b.getPosition(),c=f.pageYOffset,d=f.innerHeight,e=b.inViewport(a);e?(r=!0,b.sendMessage("window.scroll",{frameOffset:a,pageOffset:c,height:d}),b.sendMessage("window.inViewport")):
r&&!e&&(r=!1,b.sendMessage("window.scrollOffViewport"))};b.on("ready",function p(a){b.off("ready",p);s&&s.parentNode===o&&o.removeChild(s);var c={themeUrl:g.themeUrl,permalink:g.permalink,anchorColor:g.anchorColor,referrer:f.location.href,colorScheme:g.colorScheme,serif:g.serif,remoteAuthS3:g.remoteAuthS3,apiKey:g.apiKey,sso:g.sso};if(f.navigator.userAgent.match(/(iPad|iPhone|iPod)/))c.width=b.elem.offsetWidth;b.inViewport()&&b.sendMessage("window.inViewport");e.clientData=a;b.sendMessage("init",
c);e.trigger("loading.init")});b.on("resize",function(a){b.elem.style.height=a.height+"px"});b.on("reload",function(){f.location.reload()});b.on("posts.paginate",function(){e.trigger("posts.paginate")});b.on("posts.create",function(a){e.trigger("posts.create",{id:a.id,text:a.raw_message})});b.on("scrollTo",function(a){var c=b.getPosition(),c=a.relative==="window"?a.top:c.top+a.top;(a.force||!(c>f.pageYOffset&&c<f.pageYOffset+f.innerHeight))&&f.scrollTo(0,c)});b.on("fakeScroll",l);b.on("realtime.init",
function(a){for(var c=["north","south"],d,f,i=0;i<c.length;i++)f=c[i],d=new DISQUS.Sandbox({uid:"-indicator-"+f,container:e.settings.container,contents:a[f].contents,styles:a[f].styles}),d.load(),d.hide(),function(a){d.click(function(){b.sendMessage("realtime.click",a)})}(f),e.indicators[f]=d});b.on("realtime.showNorth",function(a){var b=e.indicators.north;b.document.getElementById("message").innerHTML=a;b.show()});b.on("realtime.hideNorth",function(){e.indicators.north.hide()});b.on("realtime.showSouth",
function(a){var b=e.indicators.south;b.document.getElementById("message").innerHTML=a;b.show()});b.on("realtime.hideSouth",function(){e.indicators.south.hide()});b.on("mainViewRendered",function(){DISQUS.trigger("lounge:mainViewRendered");e.trigger("loading.done")});b.load(function(){f.postMessage===h&&(b.elem.setAttribute("height","500px"),b.elem.setAttribute("scrolling","yes"),b.elem.setAttribute("horizontalscrolling","no"),b.elem.setAttribute("verticalscrolling","yes"))});d("window.hashchange",
function(a){b.sendMessage("window.hashchange",a.hash)});d("window.resize",function(){b.sendMessage("window.resize")});d("window.scroll",l);d("window.click",function(){b.sendMessage("window.click")});d("switches.changed",function(a){b.sendMessage("switches.changed",a)});e.trigger("loading.start")};e.prototype.destroy=function(){var a=this.indicators;this.off();if(this._boundGlobalEvents.length)DISQUS.off(this._boundGlobalEvents.join(" "),null,this),this._boundGlobalEvents=null;this.frame&&this.frame.destroy();
if(a.north)a.north.destroy(),a.north=null;if(a.south)a.south.destroy(),a.south=null;DISQUS.App.prototype.destroy.call(this)};var l=function(a){return new e(a)};DISQUS.extend(l,{listByKey:function(){var a={};d(function(c){a[c.uid]=c});return a},list:function(){var a=[];d(function(c){a.push(c)});return a},get:function(a){a=DISQUS.App.get(a);return a instanceof e&&a}});return{Lounge:l}});
(function(f,h,k){function d(){function a(b){var b=b.getAttribute?b.getAttribute("src"):b.src,c=[/https?:\/\/(www\.)?disqus\.com\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.disqus\.com/i,/https?:\/\/(www\.)?dev\.disqus\.org\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.dev\.disqus\.org/i],d=c.length;if(!b||b.substring(b.length-8)!="embed.js")return null;for(var e=0;e<d;e++){var f=b.match(c[e]);if(f&&f.length&&f.length==3)return f[2]}return null}for(var b=h.getElementsByTagName("script"),
c=b.length-1;c>=0;c--){var d=a(b[c]);if(d!==null)return d}return null}function j(a,b,c){var d;if(a===h)return"";f.getComputedStyle?d=h.defaultView.getComputedStyle(a,null).getPropertyValue(b):a.currentStyle&&(d=a.currentStyle[b]?a.currentStyle[b]:a.currentStyle[c]);return d=="transparent"||d===""||d=="rgba(0, 0, 0, 0)"?j(a.parentNode,b,c):d||null}function a(a){a.match("^rgb")&&(a=c(a).substr(1));var b=parseInt(a.substr(0,2),16),d=parseInt(a.substr(2,2),16),a=parseInt(a.substr(4,2),16);return(b*299+
d*587+a*114)/1E3}function c(a){function b(a){a=Number(a).toString(16);return a.length==1?"0"+a:a}if(a.substr(0,1)==="#")return a;var c=/.*?rgb\((\d+),\s*(\d+),\s*(\d+)\)/.exec(a);if(!c||c.length!==4)return"";var a=b(c[1]),d=b(c[2]),c=b(c[3]);return"#"+a+d+c}function e(a,b,c){DISQUS.isString(a)&&(a=h.createElement(a));var d=null;a.style.visibility="hidden";q.appendChild(a);d=j(a,b,c);q.removeChild(a);return d}function l(){var a=h.createElement("a");a.href=+new Date;return e(a,"color")}function i(){for(var a=
h.getElementsByTagName("h1"),b=h.title,c=b.length,d=b,e=0.6,f=0;f<a.length;f++)(function(a){var a=a.textContent||a.innerText,f;if(!(a===null||a===k)){f=0;for(var h=Array(b.length),g=0;g<=b.length;g++){h[g]=Array(a.length);for(var i=0;i<=a.length;i++)h[g][i]=0}for(g=0;g<b.length;g++)for(i=0;i<a.length;i++)b[g]==a[i]&&(h[g+1][i+1]=h[g][i]+1,h[g+1][i+1]>f&&(f=h[g+1][i+1]));f/=c;f>e&&(e=f,d=a)}})(a[f]);return d}function n(){var c=b.page,c={container:g,forum:r,anchorColor:l(),colorScheme:128<a(e("span",
"color"))?"dark":"light",sortOrder:"popular",permalink:o,serif:{courier:1,times:1,georgia:1,palatino:1}.hasOwnProperty(e("span","font-family","fontFamily").toLowerCase()),url:c.url||f.location.href.replace(/#.*$/,""),title:c.title||i(),slug:c.slug,category:c.category_id,identifier:c.identifier,apiKey:c.api_key,remoteAuthS3:c.remote_auth_s3,sso:b.sso,themeUrl:f.disqus_theme_root_url,useConman:f.disqus_demo};t=DISQUS.Lounge(c);var d={onReady:"loading.done",onNewComment:"posts.create",onPaginate:"posts.paginate"};
DISQUS.each(b.callbacks,function(a,b){d[b]&&DISQUS.each(a,function(a){t.on(d[b],a)})});t.init()}var g=f.disqus_container_id||"disqus_thread",q=h.getElementById(g),o=function(){var a=f.location.hash;return(a=a&&a.match(/comment\-([0-9]+)/))&&a[1]}(),b={page:{url:k,title:k,slug:k,category_id:k,identifier:k,api_key:k,remote_auth_s3:k,author_s3:k,developer:k},sso:{},callbacks:{preData:[],preInit:[],onInit:[],afterRender:[],onReady:[],onNewComment:[],preReset:[],onPaginate:[]}};DISQUS.each(["developer",
"shortname","identifier","url","title","category_id","slug"],function(a){var c=f["disqus_"+a];typeof c!=="undefined"&&(b.page[a]=c)});var r=f.disqus_shortname||d(),r=r.toLowerCase();if(typeof f.disqus_config==="function")try{f.disqus_config.call(b)}catch(s){}var t;h.getElementById(g).innerHTML="";n();if(f.postMessage)DISQUS.Switches({container:g}).fetch({data:{forum:r}}),DISQUS.domready(function(){if(h.getElementsByClassName){var a=h.getElementsByClassName("dsq-brlink");a&&a.length&&a[0].parentNode.removeChild(a[0])}}),
DISQUS.request={get:function(a,b,c){DISQUS.require(a,b,c)}},DISQUS.reset=function(a){a=a||{};if(typeof a.config==="function")try{a.config.call(b)}catch(c){}t&&(t.destroy(),t=null);a.reload&&n()}})(this,this.document);