var DISQUS=function(e){var h={AssertionError:function(c){this.message=c}};h.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};h.assert=function(c,d){if(!c)throw new h.AssertionError(d);};var f=[];h.define=function(c,d){typeof c==="function"&&(d=c,c="");for(var b=c.split("."),a=b.shift(),g=h,o=(d||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;return a}},e);a;)g=g[a]?g[a]:g[a]={},a=b.shift();for(var j in o)o.hasOwnProperty(j)&&
(o.__overwrites__||g[j]!==null&&h.assert(!g.hasOwnProperty(j),"Unsafe attempt to redefine existing module with "+j),g[j]=o[j],f.push(function(a,b){return function(){delete a[b]}}(g,j)));return g};h.use=function(c){return h.define(c)};h.cleanup=function(){for(var c=0;c<f.length;c++)f[c]()};return h}(this);
DISQUS.define(function(e,h){var f=e.document,c=f.getElementsByTagName("head")[0]||f.body,d={running:!1,timer:null,queue:[]};DISQUS.defer=function(b,a){function c(){var a=d.queue;if(a.length===0)d.running=!1,clearInterval(d.timer);for(var b=0,g;g=a[b];b++)g[0]()&&(a.splice(b--,1),g[1]())}d.queue.push([b,a]);c();if(!d.running)d.running=!0,d.timer=setInterval(c,100)};DISQUS.each=function(b,a){var c=b.length,d=Array.prototype.forEach;if(isNaN(c))for(var f in b)b.hasOwnProperty(f)&&a(b[f],f,b);else if(d)d.call(b,
a);else for(d=0;d<c;d++)a(b[d],d,b)};DISQUS.extend=function(b){DISQUS.each(Array.prototype.slice.call(arguments,1),function(a){for(var c in a)b[c]=a[c]});return b};DISQUS.serializeArgs=function(b){var a=[];DISQUS.each(b,function(b,c){b!==h&&a.push(c+(b!==null?"="+encodeURIComponent(b):""))});return a.join("&")};DISQUS.isString=function(b){return Object.prototype.toString.call(b)==="[object String]"};DISQUS.serialize=function(b,a,c){a&&(b+=~b.indexOf("?")?b.charAt(b.length-1)=="&"?"":"&":"?",b+=DISQUS.serializeArgs(a));
if(c)return a={},a[(new Date).getTime()]=null,DISQUS.serialize(b,a);a=b.length;return b.charAt(a-1)=="&"?b.slice(0,a-1):b};DISQUS.require=function(b,a,g,d,h){function l(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))d&&d(),k&&clearTimeout(k),DISQUS.bean.remove(a.target,p,l)}var e=f.createElement("script"),p=e.addEventListener?"load":"readystatechange",k=null;e.src=DISQUS.serialize(b,a,g);e.async=!0;e.charset="UTF-8";(d||h)&&DISQUS.bean.add(e,p,l);h&&(k=setTimeout(function(){h()},
2E4));c.appendChild(e);return DISQUS};DISQUS.requireStylesheet=function(b,a,g){var d=f.createElement("link");d.rel="stylesheet";d.type="text/css";d.href=DISQUS.serialize(b,a,g);c.appendChild(d);return DISQUS};DISQUS.requireSet=function(b,a,c){var d=b.length;DISQUS.each(b,function(b){DISQUS.require(b,{},a,function(){--d===0&&c()})})};DISQUS.injectCss=function(b){var a=f.createElement("style");a.setAttribute("type","text/css");b=b.replace(/\}/g,"}\n");e.location.href.match(/^https/)&&(b=b.replace(/http:\/\//g,
"https://"));a.styleSheet?a.styleSheet.cssText=b:a.appendChild(f.createTextNode(b));c.appendChild(a)}});
DISQUS.define("JSON",function(){function e(a){return a<10?"0"+a:a}function h(b){a.lastIndex=0;return a.test(b)?'"'+b.replace(a,function(a){var b=j[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+b+'"'}function f(a,b){var c,e,j,m,k=g,n,i=b[a];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!d&&(i=i.toJSON(a));typeof l==="function"&&(i=l.call(b,a,i));switch(typeof i){case "string":return h(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";g+=o;n=[];if(Object.prototype.toString.apply(i)==="[object Array]"){m=i.length;for(c=0;c<m;c+=1)n[c]=f(c,i)||"null";j=n.length===0?"[]":g?"[\n"+g+n.join(",\n"+g)+"\n"+k+"]":"["+n.join(",")+"]";g=k;return j}if(l&&typeof l==="object"){m=l.length;for(c=0;c<m;c+=1)e=l[c],typeof e==="string"&&(j=f(e,i))&&n.push(h(e)+(g?": ":":")+j)}else for(e in i)Object.hasOwnProperty.call(i,e)&&(j=f(e,i))&&n.push(h(e)+(g?": ":":")+j);j=n.length===0?"{}":g?"{\n"+g+n.join(",\n"+g)+"\n"+
k+"}":"{"+n.join(",")+"}";g=k;return j}}var c={},d=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+e(this.getUTCMonth()+1)+"-"+e(this.getUTCDate())+"T"+e(this.getUTCHours())+":"+e(this.getUTCMinutes())+":"+e(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var b=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,o,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;c.stringify=function(a,b,c){var d;o=g="";if(typeof c==="number")for(d=0;d<c;d+=1)o+=" ";else typeof c==="string"&&(o=c);if((l=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");return f("",{"":a})};c.parse=function(a,c){function d(a,
b){var g,e,f=a[b];if(f&&typeof f==="object")for(g in f)Object.hasOwnProperty.call(f,g)&&(e=d(f,g),e!==void 0?f[g]=e:delete f[g]);return c.call(a,b,f)}var g,a=String(a);b.lastIndex=0;b.test(a)&&(a=a.replace(b,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return g=eval("("+a+")"),
typeof c==="function"?d({"":g},""):g;throw new SyntaxError("JSON.parse");};var m={a:[1,2,3]},p,k;if(Object.toJSON&&Object.toJSON(m).replace(/\s/g,"")==='{"a":[1,2,3]}')p=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(m='{"a":[1,2,3]}'.evalJSON(),m.a&&m.a.length===3&&m.a[2]===3&&(k=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),d=!(a&&a.length===3&&a[2]===3))})();if(d||!p||!k)return{stringify:c.stringify,parse:c.parse};return{stringify:p,
parse:k}});
DISQUS.define("Bus",function(){function e(a){a=a.split("/");return a[0]+"//"+a[2]}var h=DISQUS.use("JSON"),f=window.location.hash.slice(1),c=window.parent,d=document.referrer,b={};b.client=e(document.location.href);b.host=d?e(d):b.client;return{origins:b,postMessage:function(a){a.sender=f;a=h.stringify(a);c.postMessage(a,b.host)},sendHostMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:b})},sendGlobalMessage:function(a,b){b=b||[];DISQUS.Bus.postMessage({scope:"global",name:a,
data:b})}}});_.extend(DISQUS.Bus,Backbone.Events);$(document).ready(function(){var e=window.addEventListener?window.addEventListener:window.attachEvent,h=window.addEventListener?"message":"onmessage";if(!e)throw Error("No event support.");e(h,function(e){var c=DISQUS.Bus,d=e.origin;if(!(d!=c.origins.client&&d!=c.origins.host)){var b;try{b=DISQUS.JSON.parse(e.data)}catch(a){return}e=b.data;switch(b.scope){case "client":c.trigger(e.eventName,e.data)}}},!1)});
DISQUS.define(function(e){var e=e.document,h=require("bean"),f=navigator.userAgent.match(/Android|webOS|iPhone|iPad|iPod|BlackBerry/i),c;try{localStorage.setItem("_test","_test"),localStorage.removeItem("_test"),c=!0}catch(d){c=!1}var b={blocks:{},ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",bean:h,debug:!1,browser:{mobile:f,localStorage:c,contentEditable:"isContentEditable"in e.documentElement},addBlocks:function(){return function(a){a(DISQUS)}}};
b.templateGlobals={urls:DISQUS.use("urls"),sso:null,_:{pluralize:_.pluralize}};b.renderBlock=function(a,c){return DISQUS.blocks[a](b.templateGlobals,c)};b.assureOffset=function(a){return a.indexOf("+")>=0?a:a+"+00:00"};c=b.Builder=function(){this.accum=[]};_.extend(c.prototype,{put:function(a){this.accum.push(a)},esc:function(a){return String(a).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")},compile:function(){return this.accum.join("")}});
return b});
DISQUS.define("urls",function(){return{media:"http://mediacdn.disqus.com/1344364156",root:"http://disqus.com",realertime:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+encodeURIComponent(document.referrer),help:"http://disqus.com/help/",editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",
facebook:"http://disqus.com/_ax/facebook/begin/"},loading:"http://mediacdn.disqus.com/1344364156/html/simple-loading.html",avatar:{generic:"http://mediacdn.disqus.com/1344364156/images/noavatar92.png"}}});
DISQUS.define("api",function(){function e(c){function d(a){var f=a.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,f.length)===f&&(a=DISQUS.JSON.parse(a.originalEvent.data),a.requestId==b&&(f=a.code===0?c.success:c.error,delete a.requestId,(f||function(){})(a),document.body.removeChild(h),document.body.removeChild(e),$(window).unbind("message",d)))}var b=_.uniqueId(),a=document.createElement("div"),e=document.createElement("form"),f="frame_"+b,h;a.innerHTML='<iframe name="'+f+'"></iframe>';h=a.childNodes[0];
e.target=f;e.action=c.url.replace(".json",".pm");e.method=c.method||"GET";c.data=_.extend(c.data,{callback:b,referrer:document.referrer});_.each(c.data,function(a,b){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var c=document.createElement("input");c.type="hidden";c.name=b;c.value=a;e.appendChild(c)})});$(window).bind("message",d);document.body.appendChild(h);document.body.appendChild(e);e.submit()}function h(c){c=_.defaults(c,f);c.data=c.data||{};c.data.api_key=
DISQUS.apiKey;$.ajax(c)}var f={};return{defaults:function(c){_.extend(f,c)},ajax:h,call:function(c,d){d=d||{};d.url=(d.secure?DISQUS.urls.apiSecure:DISQUS.urls.api)+c;d.data=_.extend(d.data||{},{api_key:DISQUS.apiKey});(d.secure?e:h)(d)}}});
(function(e){var h=DISQUS.Bus,f=DISQUS.urls.api+"internal/switches/list.jsonp";e.switches_jsonp_cb=function(c){h.sendHostMessage("switches.received",c.response)};h.on("fetch",function(c){c=c||{};c.data=c.data||{};c.data.callback="switches_jsonp_cb";c.data.api_key=DISQUS.apiKey;c=DISQUS.serialize(f,c.data,!1);DISQUS.require(c)});h.sendHostMessage("ready")})(this);